### ISSUE TITLE
[📖] Qwik homepage - light mode issue

### ISSUE THREAD

**Issue by thejackshelton** [BuilderIO/qwik#4040] opened 2023-05-03 14:22 UTC
### Suggestion

Whenever I click on the light mode (at least on the qwik homepage) I continue to get the dark mode version.

https://gyazo.com/0311e49bbd80155f3ae9f2403079f21f

**Comment by ulic75** [comment] 2023-05-03 14:29
Perhaps it's a design decision?  If you scroll to the footer and toggle the footer changes.

**Comment by zanettin** [comment] 2023-05-03 17:38
Hi @thejackshelton 👋 
yes this is as designed. at least by now 😃 the docs still can be toggled. also the search slot switches the colors and the footer as mentioned by @ulic75 👍 is there an issue because of this decission? thanks for creating this issue 🙏

**Comment by thejackshelton** [comment] 2023-05-03 18:43
> Hi @thejackshelton 👋 yes this is as designed. at least by now 😃 the docs still can be toggled. also the search slot switches the colors and the footer as mentioned by @ulic75 👍 is there an issue because of this decission? thanks for creating this issue 🙏

Ah gotcha. I guess I was thrown off due to the previous homepage light mode.

**Comment by zanettin** [comment] 2023-05-03 19:56
all good 👍 let me know if you miss smth and thx for all your help 🙏 gonna close this issue for now 😃

**Closed** 2023-05-03 19:57 UTC
