### ISSUE TITLE
[🐞] PropFunction cannot be passed down

### ISSUE THREAD

**Issue by juanpmarin** [BuilderIO/qwik#5663] opened 2024-01-02 19:53 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm trying to pass down an event handler between components, like this:

```tsx
import { component$, type PropFunction } from "@builder.io/qwik";

type ParentButtonProps = {
  onClick$?: PropFunction<() => unknown>;
};

export const ParentButton = component$<ParentButtonProps>(({ onClick$ }) => {
  return <ChildButton onClick$={onClick$} />;
});

type ChildButtonProps = {
  onClick$?: PropFunction<() => unknown>;
};

const ChildButton = component$<ChildButtonProps>(({ onClick$ }) => {
  return <button onClick$={onClick$}>click me</button>;
});
```

This worked in the past, but now, the linter is throwing:

```
Using "onClick$" as an event handler, however functions are not serializable.
Did you mean to wrap it in `$()`?

Fix the type of onClick$ to be PropFunction
```

Is this an expected behavior in newer versions of qwik?
How can I fix it?
I'm using qwik 1.3.2

### Reproduction

https://stackblitz.com/edit/qwik-starter-6mdst3

### Steps to reproduce

Code is in components/button/button.tsx

You can reproduce the error running `npm run lint`

### System Info

```shell
System:
    OS: Linux 6.6 Pop!_OS 22.04 LTS
    CPU: (12) x64 Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
    Memory: 13.92 GB / 31.21 GB
    Container: Yes
    Shell: 5.8.1 - /usr/bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.volta/tools/image/node/20.10.0/bin/node
    Yarn: 4.0.2 - ~/.volta/tools/image/yarn/4.0.2/bin/yarn
    npm: 10.2.3 - ~/.volta/tools/image/node/20.10.0/bin/npm
    pnpm: 8.13.1 - ~/.volta/bin/pnpm
```

**Comment by wmertens** [comment] 2024-01-04 07:52
This is an issue with the linter. The relevant code is [here](https://github.com/BuilderIO/qwik/blob/f47208ba20de72299b23f07a6df7c6dd40d4db4e/packages/eslint-plugin-qwik/src/validLexicalScope.ts#L181-L188), but I don't understand how it thinks the warning applies.

It also seems that in the stackblitz editor, everything is fine, the `onClick$` type name is `PropFnInterface`, which is what it expects.

So maybe the vite eslint instance doesn't have the correct type info?

**Comment by diecodev** [comment] 2024-01-05 23:12
This is a duplicate of my issue, i think: #5652

**Comment by wmertens** [comment] 2024-01-07 09:28
@diecodev no, looks like your issue actually has a problem with generated output, whereas this is just the linter complaining where it shouldn't

**Comment by diecodev** [comment] 2024-01-07 16:08
@wmertens Oh, mb. Sorry for the confusion.

**Comment by wmertens** [comment] 2024-01-08 13:36
There's a chance that this is fixed by #5672, but only because the types are simplified somewhat and that might make the linter happier?

**Comment by juanpmarin** [comment] 2024-01-14 01:35
@wmertens it seems that PropFunction should not be longer used, and use QRL<> instead

**Comment by wmertens** [comment] 2024-01-14 06:29
@juanpmarin yes indeed. You can just do a global search and replace.

**Closed** 2024-01-14 07:57 UTC
Labels: TYPE: bug, COMP: eslint, COMMUNITY: PR is welcomed, COMP: typing
