### ISSUE TITLE
[📖] different color schema for code elements could improve code visibility and readability

### ISSUE THREAD

**Issue by andriytyurnikov** [BuilderIO/qwik#2876] opened 2023-02-08 03:19 UTC
### Suggestion

Default contrast levels are impossible to read:
<img width="732" alt="Screenshot 2023-02-08 at 05 05 29" src="https://user-images.githubusercontent.com/3668/217420144-005b7dd1-82c7-4dc9-847e-cb4d8c325562.png">

**Comment by zanettin** [comment] 2023-02-08 06:18
Thanks @andriytyurnikov for mentioning this 🙏 imo this is a duplicate of #2871 , right?

**Comment by manucorporat** [comment] 2023-02-09 11:58
it was a bug! should be fixed now!

**Closed by manucorporat** 2023-02-09 11:58 UTC
