### ISSUE TITLE
[🐞] build script stuck after '✓ Built client modules' in adapters/static 

### ISSUE THREAD

**Issue by sirjager** [BuilderIO/qwik#5228] opened 2023-09-27 17:26 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

pnpm run build.types
pnpm run build.client
pnpm run build.server
pnpm run lint

> my-qwik-basic-starter@ build.client /qwik-app
> vite build

vite v4.4.7 building for production...
✓ 45 modules transformed.
dist/q-manifest.json       20.89 kB │ gzip:  4.22 kB
dist/build/q-a14a9229.css   6.16 kB │ gzip:  1.81 kB
dist/build/q-e6a2989e.js    0.13 kB │ gzip:  0.12 kB
dist/build/q-a66fa7f5.js    0.13 kB │ gzip:  0.13 kB
dist/build/q-22bb215a.js    0.21 kB │ gzip:  0.16 kB
dist/build/q-d710e8c5.js    0.29 kB │ gzip:  0.21 kB
dist/build/q-1783ee57.js    0.31 kB │ gzip:  0.23 kB
dist/build/q-524233b0.js    0.33 kB │ gzip:  0.26 kB
dist/build/q-e59a97ae.js    0.42 kB │ gzip:  0.29 kB
dist/build/q-d0dbc7ef.js    0.47 kB │ gzip:  0.32 kB
dist/build/q-3fbb71e6.js    0.54 kB │ gzip:  0.32 kB
dist/build/q-5f8712be.js    0.75 kB │ gzip:  0.46 kB
dist/build/q-47219ec6.js    0.76 kB │ gzip:  0.42 kB
dist/build/q-fd5e324d.js    0.79 kB │ gzip:  0.52 kB
dist/build/q-0b669ed7.js    0.89 kB │ gzip:  0.56 kB
dist/build/q-e154b310.js    1.03 kB │ gzip:  0.65 kB
dist/build/q-2db046d2.js    1.14 kB │ gzip:  0.68 kB
dist/build/q-663033b0.js    2.29 kB │ gzip:  1.11 kB
dist/service-worker.js      2.54 kB │ gzip:  1.21 kB
dist/build/q-e9c2b910.js    5.61 kB │ gzip:  2.40 kB
dist/build/q-28a85789.js    8.40 kB │ gzip:  3.99 kB
dist/build/q-42973fb1.js   46.25 kB │ gzip: 18.67 kB
✓ built in 1.27s

✓ Built client modules

### Reproduction

https://github.com/sirjager/test-qwik-app

### Steps to reproduce

- already added spare database url in .env
- database contains sample posts
- run build command

### System Info

```shell
System:
    OS: Linux 6.5 EndeavourOS
    CPU: (8) x64 AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx
    Memory: 14.63 GB / 23.16 GB
    Container: Yes
    Shell: 5.1.16 - /bin/bash
  Binaries:
    Node: 18.16.1 - /mnt/storage/programs/pnpm/node
    npm: 9.5.1 - /mnt/storage/programs/pnpm/npm
    pnpm: 8.8.0 - /mnt/storage/programs/pnpm/pnpm
  Browsers:
    Brave Browser: 117.1.58.131
    Chromium: 117.0.5938.88
  npmPackages:
    @builder.io/qwik: ^1.2.12 => 1.2.12
    @builder.io/qwik-city: ^1.2.12 => 1.2.12
    undici: 5.22.1 => 5.22.1
    vite: 4.4.7 => 4.4.7
```

**Comment by mhevery** [comment] 2023-09-27 18:42
This seems very similar to https://github.com/BuilderIO/qwik/issues/5196 Can you verify that it is not the same thing?

**Comment by mhevery** [comment] 2023-09-27 18:44
I am pretty sure that the issue is with drizzle migrator not with Qwik (see https://github.com/BuilderIO/qwik/issues/5196#issuecomment-1736312594) I am going to close the issue. If you feel it is a different issue let us know and I will reopen.

**Closed by mhevery** 2023-09-27 18:44 UTC
Labels: TYPE: bug, STATUS-1: needs triage

**Comment by sirjager** [comment] 2023-09-28 05:13
Thank you @mhevery for your response. 
I checked [#5196(comment)](https://github.com/BuilderIO/qwik/issues/5196#issuecomment-1736312594) again, 
In my case I replaced pg library with postgres , and everything was working fine.
no other changes.

Thanks again.
