### ISSUE TITLE
[🐞] incorrect lint error: must have one root element.

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#2712] opened 2023-01-24 22:02 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

```typescript
function LintError() {
  return (
    <div>
      {[].map((text) =>
        true ? <a>text</a> : text == "\n" ? <br /> : <span>{text}</span>
      )}
    </div>
  );
}
```

![image](https://user-images.githubusercontent.com/111951/214430940-17e8e0a4-39a1-4087-874b-5b2d603b7028.png)

### Reproduction

linter not part of stackblitz

### Steps to reproduce

```typescript
function LintError() {
  return (
    <div>
      {[].map((text) =>
        true ? <a>text</a> : text == "\n" ? <br /> : <span>{text}</span>
      )}
    </div>
  );
}
```

### System Info

```shell
any
```

**Comment by zanettin** [comment] 2023-01-24 22:10
Looks like a duplicate of #2685

**Comment by manucorporat** [comment] 2023-02-23 07:27
Rule was removed completely!

**Closed by manucorporat** 2023-02-23 07:27 UTC
Labels: bug, triage
