### ISSUE TITLE
[🐞] useOn*() does not work on custom event names with hyphens

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#5301] opened 2023-10-11 20:39 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

- open repro
- click button
- look at console

### Reproduction

https://qwik.builder.io/playground/#v=1.2.13&f=7Va9CsIwEH4ZIRZqNwc76KABB0UQX0AwQkCLg62D5N29n%2Fy2opROgl3aptfL3eW%2B776oaWbT6KBGedQBeRjA9Lir7I07l15i1vvYZ1wQWeEgkicNAILCvO02tgTZsVdnsAkiYH3Ybla6kReFKJqPIRUwb1NvcMSunBQQqWGJU%2FF2BJKDMxfgCu0flFjhvsgG0YpTZVmDULjyu9CVvk8U5SAy%2ByeHWwA71GrR3wHiiHPxvEBuE9OcltIMuzk6ByVQPMxEtw2HaTJuAbfXgF2%2B%2BU9bHeoDKyDzuFAmdC%2FJSt%2B%2BXlU92xF0oqCBg%2BKSXbgQ%2BBp4HnyZzNjngC90FcDFmtjCC5WyRRiWoAezhiL5uiRIsXhub%2FFn3t9j3hc

### System Info

```shell
n/a
```

### Additional Information

works if `init-editor` is renamed to `initEditor`

**Comment by mhevery** [comment] 2023-10-16 17:56
Haha, so this one kind of works as intended....
```typescript
useOnWindow(
    'init-editor',
    $(() => {
      console.log('useOnWindow: init editor');
    })
  );
```

Becames

```html
window.qwikevents.push("initEditor")
```

Which means it is `initEditor` rather than `init-editor`)

```typescript
divRef.value?.dispatchEvent(new CustomEvent('initEditor'));
```

Changing the code makes it work...

The dash to camel case is unexpected but it is the right behavior.... Wondering it we could make this more transparent in a way that is backwards compatible. 🤔

**Comment by wmertens** [comment] 2023-10-31 08:31
@mhevery maybe useOnWindow should accept the camelCase name and throw if it's kebab-case?

**Comment by mhevery** [comment] 2023-10-31 22:57
I think this works as intended. I update the documentation and will close this.

**Closed by mhevery** 2023-10-31 22:57 UTC
Labels: TYPE: bug, COMP: runtime, P1: nice to have / fix
