### ISSUE TITLE
[🐞] Website Tutorial isn't working

### ISSUE THREAD

**Issue by y471n** [BuilderIO/qwik#3094] opened 2023-02-22 23:01 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

![image](https://user-images.githubusercontent.com/2056046/220782386-6877d5ff-4362-47cb-93b0-b087eaf56b06.png)

### Reproduction

https://qwik.builder.io/tutorial/welcome/overview/

### Steps to reproduce

Go to https://qwik.builder.io/tutorial/welcome/overview/ and see the App tab is stuck in a loader, check console for details.

### System Info

```shell
Tried this using Safari and Chrome in Incognito to avoid any extensions from interfering but still didn't work.
```

**Comment by zanettin** [comment] 2023-02-23 09:33
Hi @y471n 👋 
Thanks a lot for mentioning this 🙏 Looks like it is a duplicate of #3052, right?
To enhance the overview i'll close this one but feel free to reopen it if needed 😄 
Thanks again for your help!

**Closed by zanettin** 2023-02-23 09:33 UTC
Labels: bug, triage
