### ISSUE TITLE
[🐞] response.redirect doesn't work as expected

### ISSUE THREAD

**Issue by lengzuo** [BuilderIO/qwik#2409] opened 2022-12-10 05:39 UTC
### Which component is affected?

Qwik City (routing)

### Describe the bug

I have a onGet server in layout.tsx to check for authentication for all the pages that used the same layout. I use a query string **isLoggedIn** as a flag to check for authentication. However, if i navigate to other protected page without **isLoggedIn** using <Link> or useNavigate(), the authentication check in layout.tsx should bring me back to my authentication page (/auth) as login is required, rather than allow me to stay in my protected page without  **isLoggedIn**.

Please see the sample project from [here](https://stackblitz.com/edit/qwik-starter-ul3hqf?file=src/routes/(main)/layout.tsx) 

### Reproduction

https://stackblitz.com/edit/qwik-starter-ul3hqf?file=src/routes/(main)/layout.tsx

### Steps to reproduce

1. Run `npm run dev`. 
2. Click the login button
3. U will be redirect to main page with **isLoggedIn** querystring in the url.
4. Click Other Page.
5. U will be redirect to Other Page without **isLoggedIn**. But u should be bring to /auth page for authentication without **isLoggedIn** flag. 

### System Info

```shell
N/A
```

**Comment by zanettin** [comment] 2022-12-16 21:21
Hi @lengzuo 
Thanks for opening this issue 🙏  not really sure if this is a bug or an expected behavior. by analyzing the network tab you can see, that the `q-data.json` request which returns the needed data for your SPA is actually redirected and returns the data from the `/auth` route. so the redirect does work. the issue imo is, that instead of a redirect on the server you should return any data via the `q-data.json` (just return an object from the `onGet` fn) and do a client side redirect instead. as an alternative you could use the MPA behavior by changing the `<Link />` component to regular `<a>` tag.

just my opinion and not sure what the core team thinks about it and what maybe changes with the new endpoint handling which just got merged (2h ago: https://github.com/BuilderIO/qwik/pull/2394)

**Comment by zanettin** [comment] 2023-01-12 20:50
Hi @lengzuo 👋 
Just wanted to check what the state of this issue is. Have you been able to solve it or try out the latest beta of qwik-city using the `loader$` fn? I've created a small migration guide over here #2560.

**Comment by adaliszk** [comment] 2023-02-01 21:29
After finding out how the new way works in #2560, I wanted to do a redirect. I had changed my `onGet` to the new format, but it seems that the redirect hook does not work.

My `src/routes/index.tsx`:
```typescript
import { RequestHandler } from '@builder.io/qwik-city'

export const onGet: RequestHandler = async ({redirect}) => {
    redirect(307, '/projects/')
}
```

There is no console output; the page just infinitely loads as if it never received a response.
Same with a non-async version:
```typescript
import { RequestHandler } from '@builder.io/qwik-city'

export const onGet: RequestHandler = ({redirect}) => {
    redirect(307, '/projects/')
}
```

When I swap around and set the header myself, then it does work:

```typescript
import { RequestHandler } from '@builder.io/qwik-city'

export const onGet: RequestHandler = async ({send, headers}) =>{
    headers.set('Location', '/projects/')
    send(307, 'Redirecting to /projects/')
}
```

My environment:
- Node 18.12.1
- Vite 4.0.4
- Qwik-City 0.1.0-beta9
- Qwik 0.16.2

**Comment by genki** [comment] 2023-02-11 00:22
For `loader$`, it seemed that follows the redirect location to fetch data if `throw redirect(...)`.
But if just call `redirect(...)` then the browser is navigated to the location.
Is this the spec?
In the former case, if the location is absolute URL then cause an error in `renderQData` about serializing issue that the `RedirectMessage` is not serializable.
Looking into the source, the `throw redirect(...)` doesn't expect absolute URL.

https://github.com/BuilderIO/qwik/blob/681ed8b8ab9e2a071901c8a0acb086def46829b5/packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts#L340-L346

https://github.com/BuilderIO/qwik/blob/681ed8b8ab9e2a071901c8a0acb086def46829b5/packages/qwik-city/middleware/request-handler/resolve-request-handlers.ts#L374-L384

**Comment by gioboa** [comment] 2023-08-26 12:28
throw redirect(...) Is the right way to go.
I don't understand if there are other problem to solve or if this issue is solved. cc @lengzuo

**Comment by adaliszk** [comment] 2023-08-26 14:40
Why would a throw be the right way to do anything but errors?
Throwing is for errors; a redirect is not an error but just an abbreviation for HTTP headers.

Within `loader$`, it makes sense that it redirects the page, as it is supposed to send HTTP headers to tell the browser to redirect a page. The throw within that is weird, and that should be reported as a new issue. Returning a redirect would make more sense there, as that is its normal behavior with data already; however, at the moment, I don't think there is any difference between the redirect in `RequestHandler` and within the `routeLoader$`.

**Comment by adaliszk** [comment] 2023-08-26 14:45
With `latest` the example code seems to work using the `response.redirect`:
https://stackblitz.com/edit/qwik-starter-tlhmjg?file=src%2Froutes%2F(main)%2Flayout.tsx

**Comment by adaliszk** [comment] 2023-08-26 15:32
Okay, after checking the docs of how it should be done, errors and redirects are expected to be thrown.
So, in terms of documentation and expected code, there are no issues here. However, I would still question why we abuse the exception system for this purpose, but that is a separate discussion.

**Comment by gioboa** [comment] 2023-08-26 18:03
I can understand your concern.
I close this issue because it's working as expected.

**Closed by gioboa** 2023-08-26 18:03 UTC
Labels: STATUS-3: works as expected

**Comment by hypecode-tech** [comment] 2025-01-17 03:19
Hi, there is an issue about redirect in our code we used for authentication cookies and checked inside of layout.tsx via RequestHandler it checks and do processes but not redirect 

`try {
    if (url.pathname === "/login" || url.pathname === "/endpoints/auth/login") {
      await next();
    } else {
      const token = cookie.get("token")?.value;
      if (!token) {
              throw redirect(308,"/login") // by the way I tried without throw same 
      } else {
        const decoded = jwt.verify(token, "dinkymetal.com");
        const email = (decoded as { email: string }).email;
        const user = await db.user.findUnique({
          where: { email: email },
        });
        if (user === null || user === undefined) {
              throw redirect(308,"/login") // by the way I tried without throw same 
        } else {
            await next();
        }
      } 
    }
  } catch (e) {
    console.error(e);
  }`  but when I do that `try {
    if (url.pathname === "/login" || url.pathname === "/endpoints/auth/login") {
      await next();
    } else {
      const token = cookie.get("token")?.value;
      if (!token) {
        headers.set('Location', '/login')
        send(307, 'Redirecting to /login')
      } else {
        const decoded = jwt.verify(token, "dinkymetal.com");
        const email = (decoded as { email: string }).email;
        const user = await db.user.findUnique({
          where: { email: email },
        });
        if (user === null || user === undefined) {
          headers.set('Location', '/login')
          send(307, 'Redirecting to /login')
        } else {
            await next();
        }
      } 
    }
  } catch (e) {
    console.error(e);
  }`
