### ISSUE TITLE
[🐞] Navigation Broken

### ISSUE THREAD

**Issue by n8sabes** [BuilderIO/qwik#2714] opened 2023-01-25 00:02 UTC
### Which component is affected?

Qwik City (routing)

### Describe the bug

`useNavigate()` does not work.

Navigating with `nav.path =`, as defined in the [docs](https://qwik.builder.io/qwikcity/api/#usenavigate), results in a browser error: **`Uncaught (in promise) TypeError: Cannot add property path, object is not extensible`**.

### Reproduction

localhost

### Steps to reproduce

1. `pnpm create qwik@latest` *(and then cd into new proj directory)*

3. Edit root `index.tsx` to use the [documentation example](https://qwik.builder.io/qwikcity/api/#usenavigate). 

```typescript
import { component$ } from '@builder.io/qwik';
import type { DocumentHead } from '@builder.io/qwik-city';
import { useNavigate } from '@builder.io/qwik-city';
import { Link } from '@builder.io/qwik-city';

export default component$(() => {
  const nav = useNavigate();

  return (
    <>
      <button onClick$={() => { nav.path = '/flower'; }}>This nav does NOT work</button><br />
      <Link href="/flower">This Link works</Link><br />
    </>
  );
});
```

4. pnpm dev

### System Info

```shell
System:
    OS: macOS 13.1
    CPU: (8) arm64 Apple M1
    Memory: 58.63 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.4.0 - ~/.nvm/versions/node/v19.4.0/bin/node
    npm: 8.19.2 - /opt/homebrew/bin/npm
  Browsers:
    Chrome: 109.0.5414.87
    Firefox Developer Edition: 109.0
    Safari: 16.2
  npmPackages:
    @builder.io/partytown: 0.7.5 => 0.7.5
    undici: 5.16.0 => 5.16.0
    vite: 4.0.4 => 4.0.4
```

### Additional Information

@manucorporat, is there a new way to programmatically navigate (not via links, such as when a `setTimeout` triggers)?

**Comment by n8sabes** [comment] 2023-01-25 01:00
**_WORKAROUND:_** `if (window) window.location = '/flower' as any;`

**Comment by literalpie** [comment] 2023-01-25 02:51
It's a little awkward since routing is weird in Stackblitz, but [Here's a stackblitz reproduction](https://stackblitz.com/edit/simple-qwik-starter-vskh1z?file=src%2Froutes%2Fflower%2Findex.tsx,src%2Froutes%2Findex.tsx,package.json). This seems to be an issue in 0.1.0-beta8 or beta9, but it works as expected in 0.0.128.

**Comment by n8sabes** [comment] 2023-01-25 03:38
Also, `nav` needs to support both history or no history navigation (e.g. `assign(url)` / `replace(url)`).

**Comment by zanettin** [comment] 2023-01-25 20:33
Hi @n8sabes and @literalpie 👋 
Looks like the docs are outdated in that regard 🙈  the working way since the betas of `qwik-city` is this:
```
const nav = useNavigation();
<button onClick$={() => nav('/dashboard')}>dashboard</button>
```

example usage on the `<Link>` component: https://github.com/BuilderIO/qwik/blob/main/packages/qwik-city/runtime/src/link-component.tsx#L51

I'll quickly check if smb has that already on the list within the docs squad team or create a PR to adjust that by myself. thanks for mentioning it 🙏

**Comment by manucorporat** [comment] 2023-01-26 10:21
Docs are not outdated, the new release of qwik city is not released yet :)

**Comment by n8sabes** [comment] 2023-01-26 18:04
My bad; I'm using the `main` branch for development and `nav("/rout")` works.

Two questions --

1. @manucorporat, Where in qwik-city is `nav()` actually implemented? I tried tracking it down in the sources before submitting an issue, but didn't understand the `use-functions.ts`, `use-context.ts`, logic-chain.

2. Is there an option to specify if navigation goes into the history, or not (e.g. equivalent to `assign` vs `replace`)?

Thank you.

**Comment by jwickers** [comment] 2023-02-16 04:20
This might be nice in some cases.
Also I just updated today after a few weeks on an older version, and is it just me or the navigate function does not change the URL in the browser anymore? it just seem to load the page, the location store itself is properly updated, but there is no pushstate happening anymore.

**Comment by manucorporat** [comment] 2023-03-21 18:29
Should be fixed!

**Closed by manucorporat** 2023-03-21 18:29 UTC
Labels: bug, triage
