### ISSUE TITLE
[📖] Custom Build Output doesn't work

### ISSUE THREAD

**Issue by H31t0rGamer** [BuilderIO/qwik#2942] opened 2023-02-11 22:17 UTC
### Suggestion

The guide doesn't work.

Page: https://qwik.builder.io/docs/advanced/custom-build-dir/#custom-build-output-directory

Error:

[commonjs--resolver] Cannot bundle Node.js built-in "node:url" imported from "src\entry.express.tsx". Consider disabling ssr.noExternal or remove the built-in dependency.
error during build:
RollupError: Cannot bundle Node.js built-in "node:url" imported from "src\entry.express.tsx". Consider disabling ssr.noExternal or remove the built-in dependency.
    at error (file:///D:/projetos/qwik-express-example/frontend/node_modules/.pnpm/rollup@3.12.0/node_modules/rollup/dist/es/shared/rollup.js:2088:30)
    at Object.error (file:///D:/projetos/qwik-express-example/frontend/node_modules/.pnpm/rollup@3.12.0/node_modules/rollup/dist/es/shared/rollup.js:23572:20)
    at Object.resolveId (file:///D:/projetos/qwik-express-example/frontend/node_modules/.pnpm/vite@4.0.3_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-0bae2027.js:21334:34)
    at Object.handler (file:///D:/projetos/qwik-express-example/frontend/node_modules/.pnpm/vite@4.0.3_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-0bae2027.js:44690:19)
    at file:///D:/projetos/qwik-express-example/frontend/node_modules/.pnpm/rollup@3.12.0/node_modules/rollup/dist/es/shared/rollup.js:23771:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/projetos/qwik-express-example/frontend/node_modules/.pnpm/rollup@3.12.0/node_modules/rollup/dist/es/shared/rollup.js:23671:28)
    at async resolveId (file:///D:/projetos/qwik-express-example/frontend/node_modules/.pnpm/rollup@3.12.0/node_modules/rollup/dist/es/shared/rollup.js:22615:26)
    at async ModuleLoader.resolveId (file:///D:/projetos/qwik-express-example/frontend/node_modules/.pnpm/rollup@3.12.0/node_modules/rollup/dist/es/shared/rollup.js:22879:15)
    at async Object.resolveId (file:///D:/projetos/qwik-express-example/frontend/node_modules/.pnpm/vite@4.0.3_@types+node@18.11.18/node_modules/vite/dist/node/chunks/dep-0bae2027.js:8001:10)
    at async PluginDriver.hookFirstAndGetPlugin (file:///D:/projetos/qwik-express-example/frontend/node_modules/.pnpm/rollup@3.12.0/node_modules/rollup/dist/es/shared/rollup.js:23671:28)

**Comment by EamonHeffernan** [comment] 2023-02-12 02:56
I think this is a duplicate of #2893

**Comment by H31t0rGamer** [comment] 2023-03-09 22:29
> I think this is a duplicate of #2893

No. It is not.

**Comment by gioboa** [comment] 2023-08-29 07:28
Hey @H31t0rGamer, thanks for opening this issue, I see that this config works Qwik 1.2.10, obviously something changed during this months. 😉
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.

**Closed by gioboa** 2023-08-29 07:28 UTC
Labels: COMP: docs
