### ISSUE TITLE
[DOCS] Index page styles may be broken?

### ISSUE THREAD

**Issue by leader22** [BuilderIO/qwik#554] opened 2022-05-31 00:56 UTC
> https://qwik-docs.pages.dev/

![image](https://user-images.githubusercontent.com/6259812/171072281-16b37dc3-e832-4132-a787-daa18b2c7b20.png)

This low-contrast text colors are intended?

BTW, since it seems that https://qwik.builder.io/ redirects to https://qwik.builder.io/docs/overview . Is this index page not to be public?

**Comment by manucorporat** [comment] 2022-06-07 07:47
should be fixed already! can you still reproduce the issue?

**Comment by wtho** [comment] 2022-06-12 18:24
@leader22 This issue occurs due to the use of `width: 100vw` at multiple places in the styles. As soon as the vertical scrollbar appears, the website width is wider than the viewport, and therefore a horizontal scrollbar.

One solution is to use width: 100% where applicable.

**Comment by mhevery** [comment] 2022-07-12 23:20
Closing as fixed.

**Closed by mhevery** 2022-07-12 23:20 UTC
Labels: COMP: docs
