### ISSUE TITLE
Add non-interactive CLI creation command

### ISSUE THREAD

**Issue by Nefcanto** [BuilderIO/qwik#2059] opened 2022-11-09 08:54 UTC
### Is your feature request related to a problem?

We want to try qwik. We need to be able to test qwik and its ecosystem end-to-end to make a decision for migration.

Right now, we're using Next.js, and we managed to get 90 in pagespeed. However, with Next.13, the same codebase became worse. Thus we seriously think of migrating to qwik altogether.

However, we need to test it end-to-end to make sure we can use.

One problem now is to be able to create qwik apps using CLI in a non-interactive way.

I could not find anything related to this in the docs. Thus I assume it does not exist.

In Next.js, we can write this line in our `Dockerfile` to automate qwik installation:

    RUN npx --yes create-next-app site --use-npm --js --eslint

Please add an equivalent features so that we can create a qwik app using its CLI, but non-interactivally.

### Describe the solution you'd like

I think of this code:

     npm -y create qwik@latest site_name_here --use-js --use-npm 

### Describe alternatives you've considered

No alternatives exist. We need to be able to create qwik applications automatically.

**Comment by shairez** [comment] 2023-08-13 14:07
closing as it seems like a duplicate of #4353

**Closed by shairez** 2023-08-13 14:07 UTC
Labels: enhancement, needs triage
