### ISSUE TITLE
[🐞] Server crashing due to unchecked exception in server$

### ISSUE THREAD

**Issue by e3e6** [BuilderIO/qwik#5666] opened 2024-01-05 16:47 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm using Qwik to buld the UI to control some Arduino board using johnny-five framework.
The johnny-five framework may throw an exception when it's not able to connect the board.
Connection to the board is happening inside setTimer, so I cannot catch any exception inside it.

I expected there is a way to handle unchecked exceptions, like node:process did.

### Reproduction

https://stackblitz.com/edit/qwik-starter-kadzas?file=src%2Froutes%2Findex.tsx

### Steps to reproduce

Run the reproduction url and click Init button

### System Info

```shell
The issue is reproducible in qwik.new, so I don't think you need my system info
```

**Comment by hassanzohdy** [comment] 2024-01-13 19:57
I guess it is not a Qwik issue, it is how Nodejs work, to capture any error during calling an external resource, you may wrap the connection inside a **Promise** then put the connection inside a `try...catch` block, and inside the `catch` block, just reject the promise with a connection error.

Something like this:

```tsx
const serverFunctionB = server$(function ServerB(name: string) {
  return new Promise((resolve, reject) => {
    // do some functions
    setTimeout(() => {
      reject("Something Went Wrong!");
    }, 1000);
  });
});
```

You don't need to call `setTimeout` it is just a mockup for delaying the connection, i hope this help you.

**Comment by e3e6** [comment] 2024-01-14 15:42
> inside

setTimeout is happening inside another lib, I have no control over it.

> I guess it is not a Qwik issue, it is how Nodejs work

Nodejs has node:process to capture unexpected errors, which doesn't work in qwik

**Comment by hassanzohdy** [comment] 2024-01-14 15:57
@e3e6 Can you reproduce the issue on [minimal project](https://stackblitz.com/edit/qwik-starter)?

Or write down a snippet here as an example.

**Comment by e3e6** [comment] 2024-01-14 16:43
Hi @hassanzohdy , here is an example, but it cannot be executed in the cloud due to hardware issues

https://stackblitz.com/edit/qwik-starter-3t8aqd?file=src%2Froutes%2Findex.tsx

**Comment by wmertens** [comment] 2024-01-17 16:39
I'm closing this because it's not a Qwik issue but feel free to continue the discussion in here if needed.

**Closed by wmertens** 2024-01-17 16:39 UTC
Labels: STATUS-3: works as expected

**Comment by e3e6** [comment] 2024-01-17 16:40
Hi @wmertens  how do I prevent the entire qwik server crashing? This is not happening in Node.
