### ISSUE TITLE
[🐞] Navigation Issue: Adding 'await' to 'useNavigate' in 'useTask' Causes App Freeze in QwikJS

### ISSUE THREAD

**Issue by devcaeg** [BuilderIO/qwik#5231] opened 2023-09-28 02:37 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

There's an issue with QwikJS. When trying to use "useNavigate" from "useTask", TypeScript indicates that "navigate" is asynchronous and thus requires an "await". However, when adding "await", the application becomes "frozen" and doesn't proceed with the navigation. Interestingly, if "void" is used instead of "await", the navigation works correctly.

In my opinion, it should work properly when adding "await". If not, the function type should be adjusted so it doesn't suggest it's a promise.

### Reproduction

https://stackblitz.com/edit/qwik-starter-yxwvja

### Steps to reproduce

1. Go to reproduction link
2. Run `npm install && npm run dev`
3. Click in the "Test" button (Notice how the navigation never takes place and the application "freezes")
4. Reload page
5. Click in the "Test 2" button ((Observe how everything works correctly)

### System Info

```shell
System:
    OS: macOS 14.0
    CPU: (8) arm64 Apple M2
    Memory: 190.11 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.1 - /opt/homebrew/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 9.8.1 - /opt/homebrew/bin/npm
    pnpm: 8.7.6 - /opt/homebrew/bin/pnpm
    Watchman: 2023.08.28.00 - /opt/homebrew/bin/watchman
  Browsers:
    Safari: 17.0
  npmPackages:
    @builder.io/qwik: 1.2.12 => 1.2.12 
    @builder.io/qwik-city: ~1.2.12 => 1.2.12 
    undici: 5.25.2 => 5.25.2 
    vite: 4.4.9 => 4.4.9
```

**Comment by mhevery** [comment] 2023-10-03 00:08
Hmm... Thanks for a repro...

This kind of works as intended.....

- `useTask` blocks rendering. So until `useTask` completes, rendering waits.
- `nav()` is not complete until a rendering is don.
The result is deadlock....

```typescript
  useTask$(async ({ track }) => {
    track(() => test.value);

    if (isBrowser) {
      nav('/demo/flower/').then(() => {
        console.log('works')
      });
    }
  });
```

https://stackblitz.com/edit/qwik-starter-ftbgm7

don't think we can do much about this...

**Comment by devcaeg** [comment] 2023-10-03 03:32
Thank you very much for your answer. Then I will continue to use "void" hahaha.

**Comment by mhevery** [comment] 2023-10-05 21:24
OK, I am going to close it as working as intended....

**Closed by mhevery** 2023-10-05 21:24 UTC
Labels: TYPE: bug, STATUS-1: needs triage
