### ISSUE TITLE
[🐞] Attempt to create a microfrontend fails when signals are introduced

### ISSUE THREAD

**Issue by tyler-graham-ck** [BuilderIO/qwik#2995] opened 2023-02-16 02:15 UTC
### Which component is affected?

Qwik City (routing)

### Describe the bug

Recently I started playing around with qwik because I find it a promising tool to setup a microfrontend.

I took the approach of using a `Resource` to resolve different qwik routes and outputting their html in a single route (more details in the [README](https://codesandbox.io/p/sandbox/qwik-signal-error-dtjdrm?file=%2FREADME.md) of the sandbox).

This worked reasonably well without any mangling of the html for static content, simple buttons, and even react components using `qwikify`. However, when a signal was introduced things started to fall apart.

When a signal is triggered the associated code fails to download 
correctly. The exception `QWIK ERROR Error: out of bounds inflateQrl access` is thrown.
This is thrown in [`inflateQrl`](https://github.com/BuilderIO/qwik/blob/bd4b1ba4ab89d567e4da3f1644a11477c04db87c/packages/qwik/src/core/qrl/qrl.ts#L253) via [`useLexicalScope`](https://github.com/BuilderIO/qwik/blob/bd4b1ba4ab89d567e4da3f1644a11477c04db87c/packages/qwik/src/core/use/use-lexical-scope.public.ts#L23).

I did make some attempts (not in the minimal reproduction) to clean up the html a little bit, such as deduping script tags, but this has not yielded any improvement.

### Reproduction

https://codesandbox.io/p/sandbox/qwik-signal-error-dtjdrm

### Steps to reproduce

Open the [sandbox](https://codesandbox.io/p/sandbox/qwik-signal-error-dtjdrm) or visit [this url](https://dtjdrm-5173.preview.csb.app/) with the console open and type in the text field.

Visiting [`/module-b`](https://dtjdrm-5173.preview.csb.app/module-b) by itself will show that the signal works when rendered normally.

### System Info

```shell
N/A
```

**Comment by gioboa** [comment] 2023-08-29 10:34
Hi @tyler-graham-ck , I created a [Qwik Microfrontends project](https://github.com/gioboa/qwik-microfrontends)
and in signals are working fine. I can't deep dive in your reproduction example because Qwik changed a lot in this months and in the CodeSandbox console there are few errors.
You can contribute in my MicroFrontend example if you want or you can fork it and create your own solution, it's open source and free to use.
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.

**Closed by gioboa** 2023-08-29 10:34 UTC
Labels: TYPE: bug, COMP: runtime
