### ISSUE TITLE
[✨] Make Record type serializable

### ISSUE THREAD

**Issue by lbensaad** [BuilderIO/qwik#4974] opened 2023-08-20 22:10 UTC
### Is your feature request related to a problem?

Most API calls in typescript return a Record. Currently Record type can not be used in a state because it is not serializable. It has to be wrapped in NoSerialize as a generic. This introduces another problem which makes the state not reactive as described in issue #4973 

### Describe the solution you'd like

I want to be able to use Record type in a state and be reactive without the need to wrap it in NoSerialize.

### Describe alternatives you've considered

Currently I am using NoSerialize but the problem is that I loose the reactivity. When I update a record in a state it does not reflect on the UI as shown in issue #4973

**Comment by mhevery** [comment] 2023-08-21 17:52
Can you provide a reproduction? A record is just an object literal, which is serializable in Qwik, so I am not sure what issue you are running into.

**Comment by lbensaad** [comment] 2023-08-21 18:15
@mhevery I found that my SDK call returns an object of a class named Record and not the typescript Record type.
here is my code:
```
interface ItemState {
  item?: OrderItem;
}
export default component$(() => {
  const state = useStore<ItemState>({ item: undefined });
  useVisibleTask$(async () => {
    const repo = new OrderItemRepo();
    const result = await repo!.get("2581");
    console.log(result.data);
/*************ERROR HAPPENS HERE***************/
    state.item = result.data;
/***************************************************/
  });
  return (
    <div>
      ...
    </div>
  );
});

```
The error happens in this line `state.item = result.data;`
here is the error message:
`Uncaught (in promise) Error: Value cannot be serialized because it's an instance of "Record". You might need to use 'noSerialize()' or use an object literal instead. Check out https://qwik.builder.io/docs/advanced/dollar/`
 
I came with a solution to copy each api call result in my own object, but i guess this will be resource consuming. Is there a better way to do it?.

**Comment by mhevery** [comment] 2023-08-21 18:17
Yes, we can't serialize custom classes. Can you return object literal instead?

**Comment by mhevery** [comment] 2023-08-21 18:19
So I am going to close this as working as intended / won't fix.

**Closed by mhevery** 2023-08-21 18:19 UTC
Labels: TYPE: enhancement, STATUS-2: waiting for an answer

**Comment by lbensaad** [comment] 2023-08-21 18:26
@mhevery I can not return object, the SDK is not mine. I am using PocketBase. All API calls return Record class object

**Comment by mhevery** [comment] 2023-08-21 19:05
I understand you don't own the SDK, but maybe you can copy the relevant data into the state. 

It is just not possible to serialize arbitrary classes like this. So it would be best if you found a workaround. Copying the data into an object literal is probably the easiest way to go.

**Comment by lbensaad** [comment] 2023-08-21 21:01
Ok, thanks a lot @mhevery, and keep the great work you are doing.

**Comment by lbensaad** [comment] 2023-08-21 21:43
The good news is that Pocketbase is switching from class to interface for api calls in the coming release as said here pocketbase/js-sdk#230. I tested it and it is working great now

**Comment by tigawanna** [comment] 2025-09-02 16:31
> The good news is that Pocketbase is switching from class to interface for API call results in the coming release as said here [pocketbase/js-sdk#230](https://github.com/pocketbase/js-sdk/issues/230). I tested it and it is working great now

How do you set-up pocketbase in qwik city
