### ISSUE TITLE
[🐞] optimizer generating wrong paths when moving components to new files

### ISSUE THREAD

**Issue by wmertens** [BuilderIO/qwik#5367] opened 2023-10-30 10:46 UTC
### Which component is affected?

Qwik Optimizer (rust)

### Describe the bug

See https://github.com/qwikifiers/qwik-ui/issues/453, https://github.com/wmertens/styled-vanilla-extract/issues/23 and https://github.com/BuilderIO/qwik/issues/5233

The optimizer creates a new file with components, and any imports are sometimes adjusted, but the adjusting doesn't seem to happen correctly.

### Reproduction

see the mentioned issues

### Steps to reproduce

import qwik components from a library, make sure these components import relative dependencies as well (in pnpm this includes deps that are only visible to that library).

### System Info

```shell
happens in latest, perhaps it works with v1.1 before the optimizer rewrite?
```

**Comment by mhevery** [comment] 2023-10-31 23:09
I believe this is a duplicate of #5368 and was resolved in https://github.com/BuilderIO/qwik/issues/5368 and can be closed.

**Closed** 2023-11-01 08:14 UTC
Labels: TYPE: bug, COMP: optimizer, STATUS-2: waiting for core, P2: important
