### ISSUE TITLE
[🐞] Qwik silently serialises URL and exposes it to client in "qwik/json"

### ISSUE THREAD

**Issue by mhuretski** [BuilderIO/qwik#5365] opened 2023-10-28 00:41 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

Hi,

In some cases Qwik serialises URL and exposes it to client in "qwik/json". 

When component doesn't have any imported component being put into JSX, data is serialised without URL.
```
import { $, component$ } from '@builder.io/qwik';

import AnyComp from '../comp/not-found';
import { routeLoader$ } from '@builder.io/qwik-city';

export const usePageData = routeLoader$(async () => {
  return 'a';
});

export default component$(() => {
  const data = usePageData();

  return (
    <>
      {data.value === 'a' ? (
        <button
          onClick$={$(() => {
            console.log(data.value);
          })}
        >
          click
        </button>
      ) : (
       <div />
        //  <AnyComp />
      )}
    </>
  );
});
```

```
{
  "refs": {
    "5": "2"
  },
  "ctx": {
    "1": {
      "c": "qc-s=0!"
    },
    "4": {
      "h": "3",
      "s": "2"
    }
  },
  "objs": [
    {
      "kjO6wIuhBgM": "1"
    },
    "a",
    "\\u00130! kjO6wIuhBgM",
    "\\u0002/src/routes_component_xyl1qowpydi.js#routes_component_xYL1qOwPyDI"
  ],
  "subs": [
    [
      "0 #4 kjO6wIuhBgM"
    ]
  ]
}
```

but when any component is imported and put into JSX, regardless of its internal content, even if it's empty component, much more additional data is serialised for some reason.
```
import { component$ } from '@builder.io/qwik';

const NotFound = component$(() => {
  return null;
});

export default NotFound;
```

```
import { $, component$ } from '@builder.io/qwik';

import AnyComp from '../comp/not-found';
import { routeLoader$ } from '@builder.io/qwik-city';

export const usePageData = routeLoader$(async () => {
  return 'a';
});

export default component$(() => {
  const data = usePageData();

  return (
    <>
      {data.value === 'a' ? (
        <button
          onClick$={$(() => {
            console.log(data.value);
          })}
        >
          click
        </button>
      ) : (
        // <div />
        <AnyComp />
      )}
    </>
  );
});
```

```
{
  "refs": {
    "5": "r"
  },
  "ctx": {
    "1": {
      "h": " k!",
      "w": "o",
      "c": "qc-c=0! qc-ic=9 qc-h=6! qc-l=i! qc-n=p qc-s=a! qc-a=8 qc-ir=7"
    },
    "2": {
      "h": "c",
      "s": "9"
    },
    "4": {
      "h": "b",
      "s": "r"
    }
  },
  "objs": [
    {
      "headings": "s",
      "menu": "s"
    },
    [],
    [],
    [],
    [],
    {},
    {
      "title": "d",
      "meta": "1",
      "links": "2",
      "styles": "3",
      "scripts": "4",
      "frontmatter": "5"
    },
    "\\u0012m",
    "\\u0012s",
    "\\u0012s",
    {
      "kjO6wIuhBgM": "q"
    },
    "\\u0002/src/routes_component_xyl1qowpydi.js#routes_component_xYL1qOwPyDI",
    "\\u0002/src/routeroutlet_component_e0ssidxoeam.js#RouterOutlet_component_e0ssiDXoeAM",
    "",
    "\\u0005http://localhost:5173/",
    {},
    false,
    "\\u0005http://localhost:5173/",
    {
      "url": "e",
      "params": "f",
      "isNavigating": "g",
      "prevUrl": "h"
    },
    {},
    {},
    "initial",
    {
      "type": "l",
      "dest": "e"
    },
    "\\u0002/src/qwikcityprovider_component_usetask_02wmimzeabk.js#QwikCityProvider_component_useTask_02wMImzEAbk[8 0! 9 6! s p a! j k! 7 i!]",
    "\\u00032 g n #1",
    "\\u0002/src/qwikcityprovider_component_goto_fx0bdjeja0e.js#QwikCityProvider_component_goto_fX0bDjeJa0E[8 j 7 i!]",
    "a",
    "\\u0013a! kjO6wIuhBgM",
    "\\u0001"
  ],
  "subs": [
    [
      "_1"
    ],
    [
      "_1"
    ],
    [
      "_1"
    ],
    [
      "_1"
    ],
    [
      "_1"
    ],
    [
      "_1"
    ],
    [
      "_1"
    ],
    [
      "0 o"
    ],
    [
      "0 o"
    ],
    [
      "0 #2"
    ],
    [
      "0 #4 kjO6wIuhBgM"
    ]
  ]
}
```

the problem is URL address `http://localhost:5173/` is also serialised, but we don't want to expose our infrastructural setup. 

Presence of this data looks odd.
Technically we can use proxy/middleware to strip URL out but it doesn't look like right thing to do in this case. Is there any better way to hide URL?

### Reproduction

https://stackblitz.com/edit/qwik-starter-aau7ah?file=src%2Froutes%2Findex.tsx

### System Info

```shell
"@builder.io/qwik": "^1.2.15",
"@builder.io/qwik-city": "^1.2.15",
"vite": "^4.4.11",
```

**Comment by wmertens** [comment] 2023-10-28 05:59
This is the dev build which includes information to make click-to-component work. When you run the preview you'll see that everything's fine.

**Comment by mhuretski** [comment] 2023-10-28 10:08
@wmertens I wish it was dev only but in preview URL is also shown

**{"refs":{"5":"r"},"ctx":{"1":{"h":" k!","w":"o","c":"qc-c=0! qc-ic=9 qc-h=6! qc-l=i! qc-n=p qc-s=a! qc-a=8 qc-ir=7"},"2":{"h":"c","s":"9"},"4":{"h":"b","s":"r"}},"objs":[{"headings":"s","menu":"s"},[],[],[],[],{},{"title":"d","meta":"1","links":"2","styles":"3","scripts":"4","frontmatter":"5"},"\u0012m","\u0012s","\u0012s",{"kjO6wIuhBgM":"q"},"\u0002q-1252e2bd.js#s_xYL1qOwPyDI","\u0002q-df97ceb6.js#s_e0ssiDXoeAM","","\u0005http://localhost:4173/",{},false,"\u0005http://localhost:4173/",{"url":"e","params":"f","isNavigating":"g","prevUrl":"h"},{},{},"initial",{"type":"l","dest":"e"},"\u0002q-a3e43f67.js#s_02wMImzEAbk[8 0! 9 6! s p a! j k! 7 i!]","\u00032 g n #1","\u0002q-a3e43f67.js#s_fX0bDjeJa0E[8 j 7 i!]","a","\u0013a! kjO6wIuhBgM","\u0001"],"subs":[["_1"],["_1"],["_1"],["_1"],["_1"],["_1"],["_1"],["0 o"],["0 o"],["0 #2"],["0 #4 kjO6wIuhBgM"]]}**

command to run preview
```
"preview": "qwik build preview && vite preview --open"
```

i also have deployed app to Cloudflare and get some generated domain assigned by Cloudflare but this part of app is not main entry point and dynamic domain should be hidden

**Comment by wmertens** [comment] 2023-10-28 11:40
On my phone but under the labs section of the Qwik website you can find a tool to see what is in the stored state. Maybe then you can see what uses that url

**Comment by mhuretski** [comment] 2023-10-28 12:09
Sorry, I don't quite understand the direction, are you talking about this https://qwik.builder.io/docs/labs/devtools/?
```
import("https://qwik.builder.io/devtools/json/");
```

as far as I can see it's referenced by some Context
![image](https://github.com/BuilderIO/qwik/assets/22213256/65f9e659-73b7-422e-963b-7a94a56ee363)

the only context is present in empty app is `QwikCityProvider`, I guess despite I'm not using `useLocation` anywhere in the app it might still be referenced in QwikCity, so it serialised origin it knows in its context, but qwik city doesn't serialise URL when there's no other imported component. Perhaps I'm wrong about QwikCityProvider, because it doesn't make any sense to add reference to URL if app is more complicated than one component and not to include it if app is pretty much completely empty.

**Comment by maiieul** [comment] 2023-10-28 19:59
I don't see the issue here. If you are running in dev or preview, then it's on your machine -> no exposition of your infra. If you are running in prod, then it's the prod URL that will be serialized.

See for example on this demo: https://x-stack.vercel.app/signin/

{"refs":{"2":"e","7":"j","a":"m o","i":"17 1e","l":"k","n":"b 18 9! c!","q":"17 1e","s":"17 1e"},"ctx":{"0":{"w":"e"},"1":{"h":" 14!","w":"16","c":"qc-c=0! qc-ic=a qc-h=6! qc-l=9! qc-n=17 qc-s=f! qc-a=b qc-ir=8"},"3":{"h":"1d","s":"6! 9!"},"4":{"h":" g"},"5":{"h":"p","s":"a"},"6":{"h":"v","w":"j u","s":"h j 9! 7 w"},"9":{"w":"m o"},"b":{"h":" g"},"m":{"h":"19","s":"9! b c!"}},"objs":[{"headings":"1e","menu":"1e"},[],[],[],[],{},{"title":"q","meta":"1","links":"2","styles":"3","scripts":"4","frontmatter":"5"},"\u0012s","\u0012z",{"url":"y","params":"10","isNavigating":"11","prevUrl":"12"},"\u00121e","\u00121e",{"actionPath":"1b","isRunning":"11","status":"1e","value":"1e","formData":"1e","submit":"1c"},"\u0002q-2d50d902.js#s_NDhtK0Iea5Q","\u00031 0 d #0",{"g8XUlGCLMBQ":"g"},null,"\u0013f! g8XUlGCLMBQ","\u0002q-9fc77899.js#s_Ku7AU0gi0Go[h]","\u00031 1 i #6","\u0012#b","\u0002q-b447f3f7.js#s_cy8NWc3cEuA[k]","\u00031 1 l #9","\u0002q-b447f3f7.js#s_gRkltM0g9r0[k]","\u00031 2 n #9","\u0002q-cbbe4d6e.js#s_e0ssiDXoeAM","","\u00119! @0",0,"\u0002q-9fc77899.js#s_lROQwus8zWc[9! 7]","\u00032 4 t #6","\u0002q-9fc77899.js#s_VkLNXphUh5s",true,"initial","\u0005https://x-stack.vercel.app/signin/",{"type":"x","dest":"y"},{},false,"\u0005https://x-stack.vercel.app/signin/",{},{},"\u0002q-30c30726.js#s_02wMImzEAbk[b 0! a 6! 1e 17 f! 13 14! 8 9!]","\u00032 g 15 #1","\u0002q-30c30726.js#s_fX0bDjeJa0E[b 13 8 9!]","0BV7Pjvi9oE","\u0002q-1d8ec505.js#s_D0056My74js","\u0013c! actionPath","?qaction=0BV7Pjvi9oE","\u0002q-2f92809a.js#s_A5bZC7WO00A[b 18 9! c!]","\u0002q-f98fa415.js#s_zrbrqoaqXSY","\u0001"],"subs":[["_1"],["_1","0 #3"],["_1","0 #3"],["_1","0 #3"],["_1"],["_1"],["_1","0 #3 title","0 #3 meta","0 #3 links","0 #3 styles"],["0 u"],["0 16"],["1 #4 r #3 href url","0 u isNavigating","0 #6 isNavigating"],["0 #5"],["0 16"],["_1","0 #m submit","2 #m 1a #n action actionPath"]]}

The URL being serialized is x-stack.vercel.app.

**Comment by wmertens** [comment] 2023-10-28 20:51
I wonder if it serialized the hostname of the request, but even then, I don't think it should store it? The client might be talking to a proxy with a different hostname

**Comment by mhuretski** [comment] 2023-10-29 05:44
Didn't find why in some cases url is serialised and in some is not, but found where it comes from and how to override it.

`QwikCityProvider` has this code inside

```
const urlEnv = useServerData("url");
  if (!urlEnv)
    throw new Error(`Missing Qwik URL Env Data`);
  const url = new URL(urlEnv);
  const routeLocation = useStore({
    url,
    params: env.params,
    isNavigating: false,
    prevUrl: void 0
  }, {
    deep: false
  });
```
`useServerData` and `useStore` this is where reference come from.

URL in server data can be overridden in `src/entry.ssr.tsx`.
```
const domain = import.meta.env.VITE_HOST || 'https://my-main-domain.com/'

export default function (opts: RenderToStreamOptions) {
  if (opts.serverData) {
    if (opts.serverData.url) {
      const url = new URL(opts.serverData.url)
      const newUrl = new URL(url.pathname, domain)
      opts.serverData.url = newUrl.href
    } else {
      opts.serverData.url = domain
    }
  } else {
    opts.serverData = {
      url: domain,
    }
  }

  return renderToStream(<Root />, {
    manifest,
    ...opts,
  });
}
```

**Comment by wmertens** [comment] 2023-10-31 08:27
Paging @mhevery to weigh in on this.

My intuition is that the correct hostname should be provided to the SSR host. Perhaps it's not optimal that the server URL is serialized, but at least it allows for consistent behavior.

**Comment by mhevery** [comment] 2023-10-31 23:33
I think this is working as intended. A URL is serialized with fully qualified name, as it could be anything not just a URL for the current application. QwikCity uses the `x-host` header to get your public URL. It should be up to the developer to ensure that the correct `x-host` is set.

**Comment by mhuretski** [comment] 2023-11-02 09:07
Seems it's `X-Forwarded-Host`, yes, this header hides internal URLs.

**Comment by wmertens** [comment] 2023-11-02 09:09
Closing as it's working as intended

**Closed by wmertens** 2023-11-02 09:09 UTC
Labels: COMP: qwik-city, STATUS-2: waiting for core
