### ISSUE TITLE
[🐞] vite config trailingSlash: false breaks home route

### ISSUE THREAD

**Issue by zanettin** [BuilderIO/qwik#2342] opened 2022-12-01 22:11 UTC
### Which component is affected?

Qwik City (routing)

### Describe the bug

Disabling trailing slashes on the vite config breaks the rendering of the home route. As mentioned here https://github.com/BuilderIO/qwik/issues/2262.

### Reproduction

https://stackblitz.com/edit/qwik-starter-rcw5u8?file=vite.config.ts

### Steps to reproduce

- Open the repro from above
- Wait till the preview is loaded
- Check server terminal output and you'll see a blank screen

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 12.70 GB / 64.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.13.0 - /var/folders/34/mgxs4kqs24s8kl0jfxg9jng00000gn/T/fnm_multishells/76891_1669932626637/bin/node
    Yarn: 1.22.18 - /var/folders/34/mgxs4kqs24s8kl0jfxg9jng00000gn/T/fnm_multishells/76891_1669932626637/bin/yarn
    npm: 8.1.0 - /var/folders/34/mgxs4kqs24s8kl0jfxg9jng00000gn/T/fnm_multishells/76891_1669932626637/bin/npm
  Browsers:
    Brave Browser: 104.1.42.88
    Chrome: 107.0.5304.121
    Chrome Canary: 110.0.5451.0
    Firefox: 107.0.1
    Safari: 16.0
    Safari Technology Preview: 16.4
  npmPackages:
    @builder.io/qwik: 0.15.0 => 0.15.0 
    @builder.io/qwik-city: 0.0.128 => 0.0.128 
    vite: 3.2.4 => 3.2.4
```

**Comment by adamdbradley** [comment] 2022-12-08 16:08
Should be fixed as of https://github.com/BuilderIO/qwik/pull/2385 Thanks for opening the issue.

**Closed by adamdbradley** 2022-12-08 16:08 UTC
Labels: bug, triage

**Comment by hyunjunian** [comment] 2022-12-22 02:48
@adamdbradley Thank you for your work! However, there is another problem.

When I added `{trailingSlash: false}`, the root page(`/`) is not shown.

Please check this issue.

**Comment by zanettin** [comment] 2022-12-22 22:17
Hi @hyunjunian 
Thanks for checking this 🙏  can confirm the issue on latest as well. Since there are a lot of changes in the pipeline for `qwik-city`s v`0.1.0` release, i'll wait with creating a new issue for that topic 👍  hope that is okay for you as well?

**Comment by hyunjunian** [comment] 2022-12-23 02:30
@zanettin Thank you for the answer. I checked this issue for v0.1.0 and the issue is solved.
I will use the 0.1.0-beta5 instead of 0.0.128.
Thank you for your great works on qwik!
