### ISSUE TITLE
CSS included using useStylesScoped$ disappears after re-rendering

### ISSUE THREAD

**Issue by emexal-company** [BuilderIO/qwik#1510] opened 2022-09-29 10:32 UTC
### Qwik Version

0.9.0

### Operating System (or Browser)

Chrome

### Which component is affected?

Qwik Runtime

### Expected Behaviour

Provided the following code :
```jsx
export const myComponent = component$((props: MyComponentProps) => {
    useStylesScoped$(`{
        ul.show {
            position: absolute; 
            inset: 0px auto auto 0px; 
            margin: 0px; 
            transform: translate(0px, 40px);
        }
    }`)
    const store = useStore({ open: false });

   return (
       <> 
            <button onClick$={() => store.open = !store.open}>Push me</button>
            <ul class={`${store.open ? 'show' : ''}`}></ul>
       </>);
```

I'm expecting the scoped style, to be applied to the `<ul>` tag after the button is pushed.

### Actual Behaviour

The scoped style is not applied to the `<ul>` tag after the button is clicked.

### Additional Information

My analysis : 
After the button is pushed, the css class 'show' is applied to the `<ul>` tag (during the re-rendering), but the <style> tag that was added during the first rendering is removed.

**Comment by leifermendez** [comment] 2022-09-29 14:52
Hi @emexal-company  i dont know exactly why ? or How? he  but I did replicate your exmaple in the playground and work fine

```jsx
import { component$, useStylesScoped$, useStore } from '@builder.io/qwik';


export const App = component$(() => {
  useStylesScoped$(`
    ul.show{
      background-color:red
    }
  `);

  const state = useStore({
    open: true,
  });

  return (
    <div>
      <button onClick$={() => (state.open = !state.open)}>Cambiar</button>
      <ul className={state.open ? 'show' : ''}>Hola --- {state.open}</ul>
    </div>
  );
});
```


https://qwik.builder.io/playground/#version=0.9.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3R5bGVzU2NvcGVkJTI0JTJDJTIwdXNlU3RvcmUlMjAlN0QlMjBmcm9tJTIwJyU0MGJ1aWxkZXIuaW8lMkZxd2lrJyUzQiU1Q24lNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQXBwJTIwJTNEJTIwY29tcG9uZW50JTI0KCgpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHVzZVN0eWxlc1Njb3BlZCUyNCglNjAlNUNuJTIwJTIwJTIwJTIwdWwuc2hvdyU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBiYWNrZ3JvdW5kLWNvbG9yJTNBcmVkJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlNjApJTNCJTVDbiU1Q24lMjAlMjBjb25zdCUyMHN0YXRlJTIwJTNEJTIwdXNlU3RvcmUoJTdCJTVDbiUyMCUyMCUyMCUyMG9wZW4lM0ElMjB0cnVlJTJDJTVDbiUyMCUyMCU3RCklM0IlNUNuJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDZGl2JTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQ2J1dHRvbiUyMG9uQ2xpY2slMjQlM0QlN0IoKSUyMCUzRCUzRSUyMChzdGF0ZS5vcGVuJTIwJTNEJTIwIXN0YXRlLm9wZW4pJTdEJTNFQ2FtYmlhciUzQyUyRmJ1dHRvbiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0N1bCUyMGNsYXNzTmFtZSUzRCU3QnN0YXRlLm9wZW4lMjAlM0YlMjAnc2hvdyclMjAlM0ElMjAnJyU3RCUzRUhvbGElMjAtLS0lMjAlN0JzdGF0ZS5vcGVuJTdEJTNDJTJGdWwlM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGZGl2JTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEKSUzQiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZlbnRyeS5zZXJ2ZXIudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHJlbmRlclRvU3RyaW5nJTJDJTIwUmVuZGVyT3B0aW9ucyUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWslMkZzZXJ2ZXInJTNCJTVDbmltcG9ydCUyMCU3QiUyMFJvb3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZyb290JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKG9wdHMlM0ElMjBSZW5kZXJPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBBcHAlMjAlN0QlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2h0bWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZodG1sJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiUyMiU3RCU1RA%3D%3D

**Comment by wmertens** [comment] 2022-09-29 22:36
@emexal-company note that when styles are manipulated in the client, the style tags are moved to `<head>`

**Comment by emexal-company** [comment] 2022-09-30 08:29
I checked the playground. After the button click, the <style> is moved to the head with the following content:
```html
<style q:style="8vxvbv-0">
    ul.show.⭐️8vxvbv-0{
      background-color:red
    }
</style>
```
In my case, the <style> is moved to the head with the following content:
```html
<style q:style="z7s2cu-1">{
    ul.show {
      background-color:red
    }
}</style>
```

Please note the I'm exposing a simplified version of my code here. The real code is the following:
```typescript
export const Dropdown = component$((props: DropdownProps) => {
  useStyles$(styles);
  useStylesScoped$(`
        ul.show {
            position: absolute; 
            inset: 0px auto auto 0px; 
            margin: 0px; 
            transform: translate(0px, 40px);
        }
    `);
  const store = useStore<DropdownStore>({ open: false });

  return (
    <div class="dropdown">
      <button
        type="button"
        data-bs-toggle="dropdown"
        aria-expanded="false"
        class={`btn btn-secondary dropdown-toggle ${store.open ? "show" : ""} ${props.buttonClass ?? ""}`}
        onClick$={() => (store.open = !store.open)}
      >
        <Slot name="button" />
      </button>
      <ul class={`dropdown-menu ${store.open ? "show" : ""} ${props.menuClass ?? ""}`}>
        <Slot name="item" />
      </ul>
    </div>
  );
});
```

**Comment by emexal-company** [comment] 2022-09-30 09:16
I tested my real code in the playground, and it is correctly working.

https://qwik.builder.io/playground#version=0.9.0&buildMode=development&entryStrategy=hook&files=JTVCJTdCJTIycGF0aCUyMiUzQSUyMiUyRmFwcC50c3glMjIlMkMlMjJjb2RlJTIyJTNBJTIyaW1wb3J0JTIwJTdCJTIwY29tcG9uZW50JTI0JTJDJTIwdXNlU3R5bGVzU2NvcGVkJTI0JTJDJTIwdXNlU3RvcmUlMkMlMjBTbG90JTIwJTdEJTIwZnJvbSUyMCclNDBidWlsZGVyLmlvJTJGcXdpayclM0IlNUNuJTVDbmludGVyZmFjZSUyMERyb3Bkb3duUHJvcHMlMjAlN0IlNUNuJTIwJTIwYnV0dG9uQ2xhc3MlM0YlM0ElMjBzdHJpbmclM0IlNUNuJTIwJTIwbWVudUNsYXNzJTNGJTNBJTIwc3RyaW5nJTNCJTVDbiU3RCU1Q24lNUNuaW50ZXJmYWNlJTIwRHJvcGRvd25TdG9yZSUyMCU3QiU1Q24lMjAlMjBvcGVuJTNBJTIwYm9vbGVhbiUzQiU1Q24lN0QlNUNuJTVDbmV4cG9ydCUyMGNvbnN0JTIwQXBwJTIwJTNEJTIwY29tcG9uZW50JTI0KChwcm9wcyUzQSUyMERyb3Bkb3duUHJvcHMpJTIwJTNEJTNFJTIwJTdCJTVDbiUyMCUyMHVzZVN0eWxlc1Njb3BlZCUyNCglNjAlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdWwuc2hvdyUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBwb3NpdGlvbiUzQSUyMGFic29sdXRlJTNCJTIwJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGluc2V0JTNBJTIwMHB4JTIwYXV0byUyMGF1dG8lMjAwcHglM0IlMjAlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwbWFyZ2luJTNBJTIwMHB4JTNCJTIwJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHRyYW5zZm9ybSUzQSUyMHRyYW5zbGF0ZSgwcHglMkMlMjA0MHB4KSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlN0QlMjAlMjAlMjAlMjAlMjAlMjAlNUNuJTIwJTIwJTIwJTIwJTYwKSUzQiU1Q24lMjAlMjBjb25zdCUyMHN0b3JlJTIwJTNEJTIwdXNlU3RvcmUlM0NEcm9wZG93blN0b3JlJTNFKCU3QiUyMG9wZW4lM0ElMjBmYWxzZSUyMCU3RCklM0IlNUNuJTVDbiUyMCUyMHJldHVybiUyMCglNUNuJTIwJTIwJTIwJTIwJTNDZGl2JTIwY2xhc3MlM0QlNUMlMjJkcm9wZG93biU1QyUyMiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0NidXR0b24lNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwdHlwZSUzRCU1QyUyMmJ1dHRvbiU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBkYXRhLWJzLXRvZ2dsZSUzRCU1QyUyMmRyb3Bkb3duJTVDJTIyJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMGFyaWEtZXhwYW5kZWQlM0QlNUMlMjJmYWxzZSU1QyUyMiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjbGFzcyUzRCU3QiU2MGJ0biUyMGJ0bi1zZWNvbmRhcnklMjBkcm9wZG93bi10b2dnbGUlMjAlMjQlN0JzdG9yZS5vcGVuJTIwJTNGJTIwJTVDJTIyc2hvdyU1QyUyMiUyMCUzQSUyMCU1QyUyMiU1QyUyMiU3RCUyMCUyNCU3QnByb3BzLmJ1dHRvbkNsYXNzJTIwJTNGJTNGJTIwJTVDJTIyJTVDJTIyJTdEJTYwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMG9uQ2xpY2slMjQlM0QlN0IoKSUyMCUzRCUzRSUyMChzdG9yZS5vcGVuJTIwJTNEJTIwIXN0b3JlLm9wZW4pJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NTbG90JTIwbmFtZSUzRCU1QyUyMmJ1dHRvbiU1QyUyMiUyMCUyRiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZidXR0b24lM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDdWwlMjBjbGFzcyUzRCU3QiU2MGRyb3Bkb3duLW1lbnUlMjAlMjQlN0JzdG9yZS5vcGVuJTIwJTNGJTIwJTVDJTIyc2hvdyU1QyUyMiUyMCUzQSUyMCU1QyUyMiU1QyUyMiU3RCUyMCUyNCU3QnByb3BzLm1lbnVDbGFzcyUyMCUzRiUzRiUyMCU1QyUyMiU1QyUyMiU3RCU2MCU3RCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NTbG90JTIwbmFtZSUzRCU1QyUyMml0ZW0lNUMlMjIlMjAlMkYlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGdWwlM0UlNUNuJTIwJTIwJTIwJTIwJTNDJTJGZGl2JTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEKSUzQiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZlbnRyeS5zZXJ2ZXIudHN4JTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHJlbmRlclRvU3RyaW5nJTJDJTIwUmVuZGVyT3B0aW9ucyUyMCU3RCUyMGZyb20lMjAnJTQwYnVpbGRlci5pbyUyRnF3aWslMkZzZXJ2ZXInJTNCJTVDbmltcG9ydCUyMCU3QiUyMFJvb3QlMjAlN0QlMjBmcm9tJTIwJy4lMkZyb290JyUzQiU1Q24lNUNuZXhwb3J0JTIwZGVmYXVsdCUyMGZ1bmN0aW9uJTIwKG9wdHMlM0ElMjBSZW5kZXJPcHRpb25zKSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjByZW5kZXJUb1N0cmluZyglM0NSb290JTIwJTJGJTNFJTJDJTIwb3B0cyklM0IlNUNuJTdEJTVDbiUyMiU3RCUyQyU3QiUyMnBhdGglMjIlM0ElMjIlMkZyb290LnRzeCUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBBcHAlMjAlN0QlMjBmcm9tJTIwJy4lMkZhcHAnJTNCJTVDbiU1Q25leHBvcnQlMjBjb25zdCUyMFJvb3QlMjAlM0QlMjAoKSUyMCUzRCUzRSUyMCU3QiU1Q24lMjAlMjByZXR1cm4lMjAoJTVDbiUyMCUyMCUyMCUyMCUzQ2h0bWwlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDaGVhZCUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0N0aXRsZSUzRUhlbGxvJTIwUXdpayUzQyUyRnRpdGxlJTNFJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUzQyUyRmhlYWQlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NBcHAlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTIwJTNDZGl2JTIwcSUzQXNsb3QlM0QlNUMlMjJidXR0b24lNUMlMjIlM0VEcm9wZG93biUzQyUyRmRpdiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NkaXYlMjBxJTNBc2xvdCUzRCU1QyUyMml0ZW0lNUMlMjIlM0VJdGVtMSUzQyUyRmRpdiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0NkaXYlMjBxJTNBc2xvdCUzRCU1QyUyMml0ZW0lNUMlMjIlM0VJdGVtMiUzQyUyRmRpdiUzRSU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjAlM0MlMkZBcHAlM0UlNUNuJTIwJTIwJTIwJTIwJTIwJTIwJTNDJTJGYm9keSUzRSU1Q24lMjAlMjAlMjAlMjAlM0MlMkZodG1sJTNFJTVDbiUyMCUyMCklM0IlNUNuJTdEJTNCJTVDbiU1Q24lMjIlN0QlNUQ%3D

**Comment by leifermendez** [comment] 2022-09-30 09:19
@emexal-company excelent!  If everything is ok could close the issue.

**Comment by emexal-company** [comment] 2022-09-30 09:35
It is not working in a qwik city environment. So I don't know if we should really close the issue.
May be I should share all the project ?

**Comment by leifermendez** [comment] 2022-09-30 09:43
Great! If could you share the repo is fine

**Comment by emexal-company** [comment] 2022-09-30 10:31
The project is here [qwikjs-experiment](https://github.com/emexal-company/qwikjs-experiment)
The element that should be styled after clicking on the dropdown button is identified by `document.querySelector(".dropdown > ul")`

**Comment by manucorporat** [comment] 2022-10-10 09:05
sharing all the project is usually a lot of work for the maintainer to navigate and figure out how to reproduce. Ideally what works is a simple repo case that shows the issue, playground, or stackblitz for example: https://qwik.new

This issue seems important, but i cant reproduce locally, i will fix as soon as i can reproduce!

**Comment by emexal-company** [comment] 2022-10-11 05:56
I will try to reproduce inside stackblitz and let you know. I have very few knowledge about qwik, otherwise I would have suggested to debug this by myself.

**Comment by manucorporat** [comment] 2022-10-12 08:42
Closing since the issue is caused by wrong CSS:
```jsx
    useStylesScoped$(`{ // <------
        ul.show {
            position: absolute; 
            inset: 0px auto auto 0px; 
            margin: 0px; 
            transform: translate(0px, 40px);
        }
    }`)
```
remove the brackets:
```
    useStylesScoped$(`
        ul.show {
            position: absolute; 
            inset: 0px auto auto 0px; 
            margin: 0px; 
            transform: translate(0px, 40px);
        }
  `)
```

Recommend you to write your styles in a separed .css file, so you get early warnings

**Closed by manucorporat** 2022-10-12 08:42 UTC
Labels: bug, needs reproduction, Priority

**Comment by emexal-company** [comment] 2022-10-13 06:06
My CSS is not wrong. The brackets are added by the qwick framework when he moves the content of the style tag to the head of the page.
