### ISSUE TITLE
[🐞] Qwik does not resolve dependencies of an installed package in production build

### ISSUE THREAD

**Issue by motss** [BuilderIO/qwik#5233] opened 2023-09-28 08:38 UTC
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

_This issue was discovered from https://github.com/BuilderIO/qwik/issues/5206._

Qwik Vite plugin fails to resolve and bundle dependencies of an installed package when running `qwik build`. I've tested in both compiler-less and normal [library mode](https://qwik.builder.io/docs/advanced/library/#library).

1. Compiler-less library mode - exports source files directly without any build step, works for JS and TS files.
1. Normal library mode - additional [build step](https://qwik.builder.io/docs/advanced/library/#library) with `vite` in the official docs.

Either mode fails when gets imported into a Qwik app due to failure to resolve import of dependencies, as shown below:

```sh
[vite]: Rollup failed to resolve import "classcat" from "/home/projects/qwik-starter-gbdfgt/src/s_hossqnkcoc8.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to 'build.rollupOptions.external'
```

## Expected behavior

Qwik Vite should resolve and bundle all dependencies of a package (in library mode) when running `qwik build`.

## Actual behavior

Qwik Vite fails to resolve dependencies of a packages (in library mode) when running `qwik build` and the following error is shown:

```sh
[vite]: Rollup failed to resolve import "classcat" from "/home/projects/qwik-starter-gbdfgt/src/s_hossqnkcoc8.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to 'build.rollupOptions.external'
```

The only to get around the error is to install all the dependencies of a package at the root directory, e.g. `pnpm install -w classcat`.

### Reproduction

Both modes produce the same error.

1. Compiler-less library mode - https://stackblitz.com/edit/qwik-starter-gbdfgt
1. Normal library mode - https://stackblitz.com/edit/qwik-starter-9u5g6w

### Steps to reproduce

https://github.com/BuilderIO/qwik/assets/10607759/6bcf5608-2113-4541-9066-5a289a188928

1. Click on any of the URLs in the `Reproduction` section
1. Stop the currently running terminal as the dev mode will be run automatically when you first visit the page
1. Run `pnpm install -r` to install the dependencies of all workspaces
1. Run `pnpm run preview` to build and run Qwik app
1. You should see the following error message:
   ```sh
   [vite]: Rollup failed to resolve import "classcat" from "/home/projects/qwik-starter-gbdfgt/src/s_hossqnkcoc8.js".
   This is most likely unintended because it can break your application at runtime.
   If you do want to externalize this module explicitly add it to 'build.rollupOptions.external'
   ```

### System Info

```shell
System:
    OS: macOS 13.6
    CPU: (10) arm64 Apple M1 Max
    Memory: 9.16 GB / 64.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.7.0 - ~/Library/Caches/fnm_multishells/57982_1695886335741/bin/node
    npm: 10.1.0 - ~/Library/Caches/fnm_multishells/57982_1695886335741/bin/npm
    pnpm: 8.7.6 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 117.0.5938.92
    Safari: 16.6
    Safari Technology Preview: 17.0
  npmPackages:
    @builder.io/qwik: ^1.2.12 => 1.2.12 
    @builder.io/qwik-city: ^1.2.12 => 1.2.12 
    undici: 5.25.1 => 5.25.1 
    vite: 4.4.9 => 4.4.9
```

**Comment by mhevery** [comment] 2023-10-03 00:17
I tried both StackBlitz URLs and followed the reproduction steps and everything works fine... Can you verify that the reproduction steps fail on your side?

**Comment by motss** [comment] 2023-10-03 05:50
> I tried both StackBlitz URLs and followed the reproduction steps and everything works fine... Can you verify that the reproduction steps fail on your side?

I've updated the `Steps to reproduce` section with a recording. I think it is not obvious that dev mode will be run automatically and the error occurs when running `pnpm preview`.

The recording shown below shows that the error still persists when you run `pnpm preview`:

https://github.com/BuilderIO/qwik/assets/10607759/6bcf5608-2113-4541-9066-5a289a188928

**Comment by mhevery** [comment] 2023-10-05 20:59
@wmertens you seem to be an expert on bundling issues. Can you have a look?

@motss Why do you need `classcat` with Qwik? Qwik already does that for you.

```
import { component$ } from '@builder.io/qwik';

export default component$(() => {
  return <p class={['bar', {'baz': true}, ['foo', {foobar: true}]]}>Hello Qwik</p>;
});
```
[playground](https://qwik.builder.io/playground/#v=1.2.12&f=Q0405ga0TTSQpoJtdbR6UmKRuo5CNZCuUrcCF5G1OgrR6mn5%2BSBhIAVUABWPja0dTWzDJLEBAA)

**Comment by wmertens** [comment] 2023-10-05 21:27
Yup, it looks as if the optimizer "absorbs" the .qwik.js files into the client build, losing their paths and therefore their private node_modules locations.

So if library Lib uses dep A, your app dir would be

```
/node_modules
  ...
  /Lib
    index.qwik.mjs
    /node_modules
      /A
```

And A is not accessible.

I think this could be solved by having the qwik transform store the node_modules for transformed files on their metadata and then in resolveId looking at that data and searching in those paths as well.

**Comment by motss** [comment] 2023-10-10 05:55
> @wmertens you seem to be an expert on bundling issues. Can you have a look?
> 
> @motss Why do you need `classcat` with Qwik? Qwik already does that for you.
> 
> ```
> import { component$ } from '@builder.io/qwik';
> 
> export default component$(() => {
>   return <p class={['bar', {'baz': true}, ['foo', {foobar: true}]]}>Hello Qwik</p>;
> });
> ```
> 
> [playground](https://qwik.builder.io/playground/#v=1.2.12&f=Q0405ga0TTSQpoJtdbR6UmKRuo5CNZCuUrcCF5G1OgrR6mn5%2BSBhIAVUABWPja0dTWzDJLEBAA)

@mhevery In my reduced test case, I'm passing `props.class` to `button`. By passing `props.class` to `button`, it allows the users to customize the button element based on their needs.

```ts
export const QwikButton = component$<QwikButtonProps>((props) => {
  return (
    <button
      class={classcat([classes.button, props.class])}
      ...
```

Without `classcat`, you will see the following type error:

<img width="650" alt="Screenshot 2023-10-10 at 13 49 13" src="https://github.com/BuilderIO/qwik/assets/10607759/21a8ee3a-f5dc-4e3f-8f84-e77c24a1705f">

**Comment by wmertens** [comment] 2023-10-10 11:43
@motss that's an unfortunate problem that will be resolved in the future by deprecating signals as DOM attributes.

In the meantime you can use this helper to remove the signal from your incoming class prop, and then your don't need classcat: 
https://github.com/qwikifiers/qwik-ui/blob/02acf3ef5ff2a43626c93a53e86f5ba2a4263996/packages/utils/src/types.ts#L42

**Comment by motss** [comment] 2023-10-10 13:15
> Yup, it looks as if the optimizer "absorbs" the .qwik.js files into the client build, losing their paths and therefore their private node_modules locations.
> 
> So if library Lib uses dep A, your app dir would be
> 
> ```
> /node_modules
>   ...
>   /Lib
>     index.qwik.mjs
>     /node_modules
>       /A
> ```
> 
> And A is not accessible.
> 
> I think this could be solved by having the qwik transform store the node_modules for transformed files on their metadata and then in resolveId looking at that data and searching in those paths as well.

@wmertens Thanks for the suggestion for `class`. However, it does not resolve the root issue of Qwik not being able to resolve any dependencies of an installed package.

**Comment by wmertens** [comment] 2023-10-10 13:31
Right, that's a problem that needs to be solved by the optimizer (not my wheelbarrow).

In the meantime, the workaround is probably to add the dependency to your app's package.json

**Comment by gioboa** [comment] 2023-11-01 08:23
I believe this was resolved in https://github.com/BuilderIO/qwik/issues/5367 and can be closed.

**Comment by wmertens** [comment] 2023-11-01 08:31
@gioboa I'm not quite sure, the issue is slightly different here, the imported module here is only visible to the module that the code is coming from (due to pnpm not being flat). So unless the module is referred to by absolute path it won't work?

**Comment by gioboa** [comment] 2023-11-01 08:35
🤔 I see, I reopen it.

**Closed** 2023-11-02 14:12 UTC
Labels: TYPE: bug, STATUS-1: needs triage

**Comment by motss** [comment] 2023-11-05 15:48
@wmertens Thanks for the patch. I've verified the fix on both compiler-less and lib-mode based monorepo. 👍
