### ISSUE TITLE
[🐞] Async update to signal does not update Slot content of custom component, only native element

### ISSUE THREAD

**Issue by intellix** [BuilderIO/qwik#3607] opened 2023-03-31 15:21 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm fetching data async and updating the state of a button to show that it's loading. When onClick$, I'm setting the loading signal to true and then updating tracked variables to trigger another API call. After 2 seconds of loading, loading is set back to false.

Updates:
```jsx
<button onClick$={() => {
  loading.value = true;
  variables.count = variables.count + 1;
}}>{loading.value ? 'Loading...' : 'Load more'}</button>
```

Does not update (capital B, custom component):
```jsx
<Button onClick$={() => {
  loading.value = true;
  variables.count = variables.count + 1;
}}>{loading.value ? 'Loading...' : 'Load more'}</Button>
```

Custom component looks like:
```jsx
<button disabled={loading} onClick$={onClick$} class="btn">
  <Slot />
</button>
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-xbedvz

### Steps to reproduce

Go to stackblitz, click either the native or the custom component button

### System Info

```shell
Chrome: v111
```

### Additional Information

I'm using tailwind so have created a custom Button component so that I avoid redeclaring the same classes throughout my application.

**Comment by akshatgarg12** [comment] 2023-04-03 05:49
```
<Button onClick$={() => {
  loading.value = true;
  variables.count = variables.count + 1;
}}>
   <>{loading.value ? 'Loading...' : 'Load more'}</>
</Button>
```

Wrapping the Slot value in fragments, makes it work as intended.

**Comment by motss** [comment] 2023-05-22 11:26
It seems like `Slot` is not able to slot text node during runtime. It works when you wrap the slotted content with a `Fragment`, like so `<>{...}</>`.

See this working [code](https://stackblitz.com/edit/qwik-starter-52rhhz).

**Comment by gioboa** [comment] 2023-09-14 11:46
Hey @intellix, thanks for opening this issue, I saw that your example works with the last version of Qwik, btw a lot of things happened during this months. 🚀
So I'm closing this issue for now, feel free to re-open it if it's still an issue for you.

**Closed by gioboa** 2023-09-14 11:46 UTC
Labels: TYPE: bug, STATUS-1: needs triage
