### ISSUE TITLE
[BUG] There is a debugger

### ISSUE THREAD

**Issue by do-diegoortiz** [BuilderIO/qwik#788] opened 2022-07-18 14:02 UTC
### Qwik Version

0.0.36

### Operating System (or Browser)

Windows + Chrome

### Which component is affected?

Qwik Runtime

### Expected Behaviour

To not have a debugger in line:
https://github.com/BuilderIO/qwik/blob/e829e5fda4028a05f326752f39af17d48592584c/packages/qwik/src/core/util/log.ts#L20

### Actual Behaviour

The apps stops trying to render this logErrorAndStop

**Comment by manucorporat** [comment] 2022-07-18 14:41
why is this not expected? in fact it's called `logErrorAndStop()` to help developers debug the issue

**Comment by mhevery** [comment] 2022-07-20 20:32
I think this is working as intended. Closing.

**Closed by mhevery** 2022-07-20 20:32 UTC
Labels: bug

**Comment by do-diegoortiz** [comment] 2022-07-21 04:00
Sorry @manucorporat I was wired to think a debugger in the code was always an error 😅  my bad!

**Comment by shairez** [comment] 2022-07-21 09:50
No worries @do-diegoortiz , yeah a debugger often does look like a bug, maybe we should add comment to the source code to make it clearer (wanna create a PR? :) 

At any case, thanks for the report!  🙏
