### ISSUE TITLE
Internal assert Internal assert, this is likely caused by a bug in Qwik: If qSerialize is true then fnStr must be provided.

### ISSUE THREAD

**Issue by acoreyj** [BuilderIO/qwik#4692] opened 2023-07-02 16:22 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

 Internal assert, this is likely caused by a bug in Qwik: If qSerialize is true then fnStr must be provided.

Reproduction:
https://stackblitz.com/github/genie-design/qwikbits-docs?file=README.md

### Reproduction

https://stackblitz.com/github/genie-design/qwikbits-docs?file=README.md

### Steps to reproduce

Load any page in dev mode

### System Info

```shell
'@builder.io/qwik':
    specifier: 1.2.3
    version: 1.2.3(undici@5.22.1)
  '@builder.io/qwik-auth':
    specifier: ~0.1.0
    version: 0.1.0(@auth/core@0.9.0)(@builder.io/qwik-city@1.2.3)(@builder.io/qwik@1.2.3)
  '@builder.io/qwik-city':
    specifier: ~1.2.3
    version: 1.2.3
  '@
```

**Comment by gustavocadev** [comment] 2023-07-03 00:10
It's the same error #4679, not sure if this happens for other reasons

**Comment by acoreyj** [comment] 2023-07-03 00:21
@manucorporat I see you fixed a similar bug.

This seems to happen with I include built components from my library (built with npx vite build --mode lib) but not if the same component is built as part of a qwik site

**Comment by anartzdev** [comment] 2023-07-04 05:13
The same thing happens to me when I also work with the libraries, and I have tried with the latest version (1.2.3) and also with 1.1.5.

I don't know what it could be, since randomly if I create a project, sometimes it works for me and sometimes it doesn't, where it gives me the error you describe.

For more info, I've tested it with Node versions 16 and 18 as well.

At the moment, I have managed to create a library template, adding some changes based on my tastes and I have it hanging, in case someone wants to develop a library. Based on this template, I'll make a little CLI with examples with simple things, using external dependencies,...I'd like to have it soon, but for now I've managed to get out of this problem with a project without problems (although there are some when they are generated) . Let's see if there is luck and a solution is found soon.

Little more I can say.

Greetings

**Comment by manucorporat** [comment] 2023-07-05 09:26
Should be fixed in 1.2.4! but libraries built with 1.2.3 could be broken! need a re-released!

We added new tests to ensure we never get this regression again

**Closed by manucorporat** 2023-07-05 09:26 UTC
Labels: bug, triage

**Comment by anartzdev** [comment] 2023-07-05 09:53
Thanks @manucorporat 👍

**Comment by r6203** [comment] 2024-07-15 15:46
Have the same error when including a Qwik library and using a specific component. When including my component directly into my app the error is fixed.
Commenting here instead of creating a new issue because I can't link to any reproducible code.
