### ISSUE TITLE
[🐞] Link component causes Resource component to throw an error on page redirect

### ISSUE THREAD

**Issue by ssmlee04** [BuilderIO/qwik#2544] opened 2023-01-02 14:10 UTC
### Which component is affected?

Qwik City (Routing)

### Describe the bug

I had a component structured very similar to this. 

```
interface ApiData {
  profile: any,
}

export const onGet: RequestHandler<ApiData> = async ({ params }: any) => { 
  try {
    const profile = await getData("AAPL");
    return {
      profile
    }
  } catch(err) {
    return {
      profile: {}
    }
  }
};

export default component$(() => {
  const mainData = useEndpoint<ApiData>();
  return (
    <Resource
      value={mainData}
      onPending={() => <>Loading...</>}
      onRejected={() => <>Error loading data</>}
      onResolved={({ profile }) => {
        const name = profile.name
        return (<>
          <div class='app-container'>
            ...
          </div>
        </>)
      }}
    />
  );
});
```

My expectation is onGet would at worse have profile = {} but I noticed when I am navigating away from this route (say if you're going to '/' from '/stocks/aapl') the profile object would become undefined. 

<img width="630" alt="image" src="https://user-images.githubusercontent.com/5617280/210242598-c5b00edd-be8b-4aa2-ba5e-b219b59604cd.png">

### Reproduction

https://github.com/ssmlee04/qwik-link-resource-bug

### Steps to reproduce

`npm start` and then follow the instructions on the readme.md

### System Info

```shell
System:
    OS: macOS 11.2.3
    CPU: (8) x64 Apple M1
    Memory: 37.35 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 16.13.1 - ~/.nvm/versions/node/v16.13.1/bin/node
    Yarn: 1.22.18 - ~/.nvm/versions/node/v16.13.1/bin/yarn
    npm: 8.1.2 - ~/.nvm/versions/node/v16.13.1/bin/npm
  Browsers:
    Chrome: 108.0.5359.124
    Firefox: 106.0.5
    Safari: 14.0.3
  npmPackages:
    @builder.io/qwik: 0.16.1 => 0.16.1
    @builder.io/qwik-city: 0.0.128 => 0.0.128
    vite: 4.0.1 => 4.0.1
```

**Comment by cmbartschat** [comment] 2023-01-04 20:28
Related: https://github.com/BuilderIO/qwik/issues/1484 https://github.com/BuilderIO/qwik/issues/1398

Hopefully when server actions/functions come out, the issue will no longer occur.

**Comment by zanettin** [comment] 2023-01-05 22:13
Hi @ssmlee04 and @cmbartschat 

Thanks for creating this issue and the reproduction 🙏 
I've just played around with the latest versions and it looks like it solves the mentioned issue. Do you want to test it as well?

made changes:
- `package.json`
  - upgrade `qwik` to `0.16.2`
  - upgrade `qwik-city` to `0.1.0-beta8`
- change `onGet` method as described below:
```
// from
export const onGet: RequestHandler<ApiData> = async ({ params }: any) => { 

// to
export const getStockData: RequestHandler<ApiData> = loader$(async ({ params }: any) => {
```
- import `loader$` from `qwik-city`
- replace `const mainData = useEndpoint<ApiData>();` with `const mainData = getStockData.use();`

**Comment by ssmlee04** [comment] 2023-01-08 04:42
@zanettin I'll get back to you on that but might take a while since the qwik-city upgrade is quite a change. Thanks!

**Comment by zanettin** [comment] 2023-01-09 06:34
Hi @ssmlee04 👋  sure take your time 👍 It was also new to me. Thats why i've noted down all the changes i found along the transition here https://github.com/BuilderIO/qwik/issues/2560. And had the same issue with the head but it's resolved and also noted above 😄

**Comment by ssmlee04** [comment] 2023-01-11 03:46
@zanettin after making changes per your suggestion this issue goes away. Thank you!

**Comment by zanettin** [comment] 2023-01-11 04:29
@ssmlee04 excellent! happy to read that 🎉 would be amazing if you could close the issue then 🙏 happy coding ans thanks again for creating the issue!

**Closed** 2023-01-11 20:03 UTC
Labels: bug, triage
