### ISSUE TITLE
[🐞] `locale` does not change the locale 

### ISSUE THREAD

**Issue by GijsW01** [BuilderIO/qwik#3221] opened 2023-03-01 13:54 UTC
**Which component is affected?**

Qwik, Qwik City

**Describe the bug**

I'm trying to localize a Qwik website, for that I use the `qwik-speak` dependency. But when I try to change to locale based on the 'accept-lang' request header. Qwik does not change the language in the context.

Below is my ./layout.tsx
```
...

export const onRequest: RequestHandler = ({ request, locale }) => {
    const acceptLanguage = request.headers.get('accept-language')
    const lang = acceptLanguage?.split(',')[0]
    locale(lang || config.defaultLocale.lang)
}

export default component$(() => {
...
```
After changing the locale the 'lang' param of `$((lang: string, asset: string, origin?: string) => {})` is still the default language.

**Steps to reproduce**

Try to change the locale like done above in Qwik 0.20.

**System Info**
```
 "@builder.io/qwik": "^0.20.0",
 "@builder.io/qwik-city": "^0.5.2",
```

**Comment by manucorporat** [comment] 2023-03-01 18:03
how can i reproduce? i see you shared some piece of code, but i can immediate reproduce, i can triage it faster and prioritize it!

**Comment by robisim74** [comment] 2023-03-01 21:45
@GijsW01 Problems with `qwik-speak` package should be opened in https://github.com/robisim74/qwik-speak/issues, because it is not an official package by Qwik team

I opened a new issue for this problem, because it depends on the Qwik `locale `function, which doesn't seem to be working: https://github.com/BuilderIO/qwik/issues/3228

**Comment by GijsW01** [comment] 2023-03-02 10:21
Moved to #3228

**Comment by zanettin** [comment] 2023-03-03 05:47
Thanks @GijsW01 and @robisim74 for creating the issues 🙏 i'll close this one in favour of #3228 👍

**Closed** 2023-03-03 05:48 UTC
Labels: bug, duplicate
