### ISSUE TITLE
`useContext()` can not be found for `Link` when conditionally rendered with updates from `useClientEffect$`

### ISSUE THREAD

**Issue by jessezhang91** [BuilderIO/qwik#1971] opened 2022-11-03 13:20 UTC
### Qwik Version

0.12.1

### Operating System (or Browser)

Mac OSX

### Which component is affected?

Qwik City

### Expected Behaviour

I do not expect to see this error when conditionally rendering `Link`s based on a value updated in `useClientEffect$`.

### Actual Behaviour

Reproduced here: https://stackblitz.com/edit/qwik-starter-z3bthd?file=src/root.tsx

Error:
```
Code(13): Actual value for useContext() can not be found, make sure some ancestor component has set a value using useContextProvider() Error: Code(13): Actual value for useContext() can not be found, make sure some ancestor component has set a value using useContextProvider()
    at logError (https://qwik-starter-z3bthd--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=a877a9a1:61:54)
    at logErrorAndStop (https://qwik-starter-z3bthd--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=a877a9a1:67:17)
    at qError (https://qwik-starter-z3bthd--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=a877a9a1:132:12)
    at useContext (https://qwik-starter-z3bthd--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=a877a9a1:1921:11)
    at useNavigate (https://qwik-starter-z3bthd--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik-city/index.qwik.mjs?v=a877a9a1:126:29)
    at Link_component_mYsiJcA4IBc (https://qwik-starter-z3bthd--5173.local-credentialless.webcontainer.io/src/link_component_mysijca4ibc.js?v=a877a9a1:9:17)
    at invoke (https://qwik-starter-z3bthd--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=a877a9a1:636:26)
    at https://qwik-starter-z3bthd--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=a877a9a1:6150:28
    at async Promise.all (index 0)
    at async Promise.all (index 0)
    at async renderMarked (https://qwik-starter-z3bthd--5173.local-credentialless.webcontainer.io/node_modules/@builder.io/qwik/core.mjs?v=a877a9a1:4471:25)
```

**Comment by manucorporat** [comment] 2022-11-03 15:35
it's a bug, but it's not about waking up, it's about the context was not serialized, when it should, I will look into it with priority

**Comment by ramsaylanier** [comment] 2022-11-03 23:08
probably the same issue but this is happening when conditionally rendering links in a Resource as well.

**Comment by jmsegrev** [comment] 2023-11-29 20:37
Im having this exact same problem qwik v1.2.19

**Comment by wmertens** [comment] 2023-11-30 05:43
@jmsegrev minimaal repro please, preferably in the playground.

Are you sure it's not because you're rendering slots optionally and the children don't see the context provided by a needed slot?

**Comment by bcha92** [comment] 2023-12-02 18:10
Same error code 13 problem also occuring as of qwik@1.2.18 when trying to "mock" `useNavigate()` using vitest. Changing the `<Link>` component to a `<a>` didn't work either.

**Comment by tri2820** [comment] 2024-02-28 07:15
This issue still persists with 
```
"@builder.io/qwik": "^1.4.5",
 "@builder.io/qwik-city": "^1.4.5",
```

Minimal example (nearly the same as what @jmsegrev given above)
```
import { component$, useSignal } from "@builder.io/qwik";
import { Link, type DocumentHead } from "@builder.io/qwik-city";

export default component$(() => {
  const clicked = useSignal(false);
  return (
    <>
      <button
        onClick$={() => {
          clicked.value = true;
          console.log("what");
        }}
      >
        Click me
      </button>
      {clicked.value && <Link href="https://google.com">What</Link>}
    </>
  );
});
```

@wmertens Can we re-open the issue?

**Comment by wmertens** [comment] 2024-02-28 08:35
The reason is that in this repro nothing is using the qwik city context during SSR, so it's not sent along with the state.

**Comment by wmertens** [comment] 2024-02-28 08:38
Actually, this is basically a duplicate of #5411

**Closed by wmertens** 2024-02-28 08:38 UTC
Labels: TYPE: bug, P3: urgent
