### ISSUE TITLE
[✨] Better either/or typings for route action values

### ISSUE THREAD

**Issue by kfranqueiro** [BuilderIO/qwik#5065] opened 2023-08-31 00:39 UTC
### Is your feature request related to a problem?

I've been trying out Qwik and really like some of its ideas, but have run into a significant developer ergonomics issue when using `routeAction$`.

It seems that when working with an action's resolved value, the return typing is forcibly converted to a partial, even when the callback would otherwise produce an object with required properties.

For example, if I write the following:

```ts
export const useFoo = routeAction$(async () => ({ foo: 42 }));
```

I get a typing like `{ foo?: number | undefined }` even though foo is definitely always defined as returned by my function.

In the case where a zod schema is also passed, I receive a similarly-partial typing:

```ts
{
  foo?: number | undefined;
  formErrors?: undefined;
  fieldErrors?: undefined;
  failed?: undefined;
} | {
  foo?: undefined;
  formErrors?: string[] | undefined;
  fieldErrors: { ... } | undefined;
  failed?: true | undefined;
}
```

This makes it onerous to pick out individual properties on successful values, requiring type assertions or redundant conditions for every individual property accessed in order to appease tsc, even though IIUC we should know which side of the union we're on as soon as we note the presence/absence of any one of our properties (or `failed`).

### Describe the solution you'd like

In the no-schema case, I would expect exactly the type my function returns: `{ foo: number }`.

In the case of passing a zod schema, I would expect either the type my function returns, or a type with only the failure-related properties, ideally definitely defined (though I'm unsure if there are implementation details that would preclude that):

```ts
{
  foo: number
} | {
  formErrors: string[];
  fieldErrors: { ... };
  failed: true;
}
```

This should make it trivial to access any number of properties on the return value within a single `if (!value.failed)` check, with no need for type assertions, or redundant conditions.

### Describe alternatives you've considered

As mentioned above, currently I'd need to work around this by adding type assertions or redundant conditions. Alternatively, I'm otherwise contemplating switching to using `server$` for my particular use cases at the moment, but I'd lose out on built-in zod support.

### Additional context

The oops-all-partials typings appear to originate in `StrictUnion`, which uses `Prettify` and `StrictUnionHelper`, both of which seem to involve use of `Partial`. I'm not sure what the goal was in building `StrictUnion` this way, or if there's some reason/limitation for the current typings conundrum.

`StrictUnion` also appears to be used in `routeLoader$` typings specifically when multiple arguments are passed, which I'm not sure is even documented?

**Comment by wtlin1228** [comment] 2023-09-01 18:07
Hi @kfranqueiro,

I believe the type definition for `useFoo` as `{ foo?: number | undefined }` is accurate because it reflects the expected behavior of the action. The `action` should have an undefined value for `foo` before it is submitted. On the other hand, when using a loader without any validation and the `fail(...)` method, it will return an object with `{ foo: number }`. This is because route loaders always execute on the server when you navigate to the corresponding route.

Here's the TypeScript code to illustrate this:

```ts
export const useFooAction = routeAction$(async () => ({ foo: 42 }));
export const useFooLoader = routeLoader$(async () => ({ foo: 42 }));

export default component$(() => {
  const fooAction = useFooAction();
  fooAction.value?.foo // (property) foo?: number | undefined

  const fooLoader = useFooLoader();
  fooLoader.value.foo // (property) foo: number
}
```
In the scenario where validation is applied, your expected response type could indeed lead to the following error. Thus, it appears that the current typing is appropriate:

```ts
type Res = {
  foo: number
} | {
  formErrors: string[];
  fieldErrors: {
    bar: string,
  };
  failed: true;
}

let res: Res
res.failed // ❌ Property 'failed' does not exist on type 'Res'.
           //    Property 'failed' does not exist on type '{ foo: number; }'.
```

**Comment by kfranqueiro** [comment] 2023-09-04 16:15
Hi, thanks for the detailed reply, and sorry my brain wasn't quite firing on all cylinders in the initial report.

You're right that my idea of excluding `failed` completely from the successful side of the union would cause `if (!res.failed)` to not compile. On the other hand, `if (!("failed" in res))` ought to work, but I guess that might be considered a bit onerous? Otherwise, if this tweak to my original suggestion were feasible, it would allow the former to work:

```ts
{
  foo: number; // Result properties preserved as required (non-partial) on "success" side
  failed?: undefined; // failed will always be falsy on "success" side
} | {
  formErrors: string[];
  fieldErrors: { ... };
  failed: true; // failed will always be truthy on the "failure" side of the union
}
```

Meanwhile, RE this remark:

> The action should have an undefined value for foo before it is submitted.

Wouldn't `action.value` be _completely_ undefined before it's submitted? i.e. there's nothing for `foo` to even exist on? In your case above where you write `fooAction.value?.foo // (property) foo?: number | undefined`, it's `value` that's really undefined, not `foo`.

I don't think this in itself should preclude the idea of returning a non-partial-ized value type in the success case.

To better illustrate the point of this feature request, in the following example I don't think I should need to resort to assertions - I know that if `failed` is falsy _or_ `foo` is truthy then `bar` should also be truthy, and the typings produced should be able to infer that as well.

```ts
  export const useFooAction = routeAction$(
    async () => ({ foo: 42, bar: 43 }),
    zod$({ foo: z.number(), bar: z.number() })
  );

  // ... inside component, after action has been submitted ...

  // This currently requires ! to avoid type errors, but shouldn't.
  // If value is defined and failed isn't, then foo/bar definitely are defined as per our action function
  if (action.value && !action.value.failed)
      console.log(action.value.foo!, action.value.bar!);

  // This won't cause type errors,
  // but if you examine `bar` in action.value.bar its typing is number | undefined,
  // even though we know it should definitely be a number since we clearly have a successful result.
  if (action.value?.foo)
    console.log(action.value.foo, action.value.bar);
```

**Comment by wtlin1228** [comment] 2023-09-04 19:11
Certainly, I appreciate the thorough explanation.

**Comment by mhevery** [comment] 2023-09-05 16:24
So I have created a #5079 but it is very breaky to existing code. So my current thinking is that we leave this as is. 

In which case do you think it makes sense to keep this issue open? or to close it?

**Comment by kfranqueiro** [comment] 2023-09-05 22:18
After spending a while messing around and comprehending what the current typings were accomplishing, I came up with an alternative approach that I think avoids breaking any current patterns while accomplishing what I was looking for: #5113

For anyone who wants to apply a patch, it'd look something like this: (generated with `patch-package` against 1.2.10)

```diff
diff --git a/node_modules/@builder.io/qwik-city/index.d.ts b/node_modules/@builder.io/qwik-city/index.d.ts
index b5a5257..89d711e 100644
--- a/node_modules/@builder.io/qwik-city/index.d.ts
+++ b/node_modules/@builder.io/qwik-city/index.d.ts
@@ -461,10 +461,6 @@ export declare interface PageModule extends RouteModule {
  */
 export declare type PathParams = Record<string, string>;
 
-declare type Prettify<T> = {} & {
-    [K in keyof T]?: T[K];
-};
-
 /**
  * @public
  */
@@ -633,9 +629,9 @@ export declare type StaticGenerateHandler = ({ env, }: {
     env: EnvGetter;
 }) => Promise<StaticGenerate> | StaticGenerate;
 
-declare type StrictUnion<T> = Prettify<StrictUnionHelper<T, T>>;
+declare type StrictUnion<T> = StrictUnionHelper<T, T>;
 
-declare type StrictUnionHelper<T, TAll> = T extends any ? T & Partial<Record<Exclude<UnionKeys<TAll>, keyof T>, never>> : never;
+declare type StrictUnionHelper<T, TAll> = T extends any ? T & Partial<Record<Exclude<UnionKeys<TAll>, keyof T>, undefined>> : never;
 
 /**
  * @public
```

**Comment by mhevery** [comment] 2023-09-06 18:31
I don' think that is correct either, as it assumes that all parts (valid and error state) are present.

**Comment by kfranqueiro** [comment] 2023-09-06 19:35
> I don' think that is correct either, as it assumes that all parts (valid and error state) are present.

What you're describing is already the case with the existing code, though, except worse because _both_ sides become optional, which is what causes this issue.

What the patch fixes is that the inapplicable parts are optional and _always_ undefined.

Going back to this example of code running after `action.submit`:

```ts
if (!result.value.failed)
  console.log(result.value.foo.answer, result.value.bar.answer);
else
  console.log(result.value.fieldErrors);
```

Here's a look at the typings of `result.value` on each side of the branch, before and after the patch:

### `!failed` branch

#### Existing typings (before patch)

```
{
    foo?: {
        answer: number;
    } | undefined;
    bar?: {
        answer: number;
    } | undefined;
    formErrors?: undefined;
    fieldErrors?: undefined;
    failed?: undefined;
} | {
    formErrors?: string[] | undefined;
    fieldErrors?: {
        ...;
    } | undefined;
    failed?: true | undefined;
    foo?: undefined;
    bar?: undefined;
}
```

(Notice TS can't rule out either side of the union, because `failed`'s typing gets partial-ized even on the side where it should always be `true`)

#### New typings (after patch)

```
{
    foo: {
        answer: number;
    };
    bar: {
        answer: number;
    };
    formErrors?: undefined;
    fieldErrors?: undefined;
    failed?: undefined;
}
```

### `else` branch

#### Existing typings (before patch)

```
{
    formErrors?: string[] | undefined;
    fieldErrors?: {
        ...;
    } | undefined;
    failed?: true | undefined;
    foo?: undefined;
    bar?: undefined;
}
```

#### New typings (after patch)

```
{
    formErrors: string[];
    fieldErrors: {
        input?: string[] | undefined;
    };
    failed: true;
    foo?: undefined;
    bar?: undefined;
}
```

**Comment by mhevery** [comment] 2023-09-08 18:14
I have re-opened https://github.com/BuilderIO/qwik/pull/5131 to dig into it more...

**Comment by mhevery** [comment] 2023-09-08 18:22
Would appreciate a review of #5131 to get your thoughts if you think it fixes the issue?

**Closed** 2023-09-08 19:43 UTC
Labels: TYPE: enhancement, STATUS-1: needs triage
