### ISSUE TITLE
[🐞] is not defined error when i used dynamic generated color variables

### ISSUE THREAD

**Issue by hosseinitabar** [BuilderIO/qwik#5208] opened 2023-09-24 09:41 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm trying to lazily load some CSS variables (mostly colors) to be used by Tailwind CSS:

its sample of this pure CSS file that import from external file and added in route-head.tsx (/src/components/router-head/route-head.tsx):
```
:root {
    --color1: #ff0000;
    --color2: #594c3e;
}
```

This is part of my tailwind.config.js file:

```
    theme: {
        extend: {
            colors: {
                custom: {
                    color1: 'var(--color-1)'
                }
            },
```
And this is the colors.css file that is loaded when page loads in production. It's not part of the build:

```
:root {
    --color-1: #ff0000;
}
```

And when I run my project, I can see that colors.css is loaded, and I can see that the HTML element has these styles applied to them (via Tailwind's compiled styles):

```
#some-element {
    background-color: var(--color-1) !important;
}
```

Yet when I hover over var(--color-1) the Chrome DevTools tells me that the `variable is not defined`.

### Reproduction

https://stackblitz.com/edit/qwik-starter-deuohs

### Steps to reproduce

Open the link of [Minimal reproducible example](https://stackblitz.com/edit/qwik-starter-deuohs)

### System Info

```shell
System:
  OS: Linux 6.2 Debian GNU/Linux 11 (bullseye) 11 (bullseye)
  CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Memory: 26.09 GB / 31.12 GB
  Container: Yes
  Shell: 5.1.4 - /bin/bash
Binaries:
  Node: 18.18.0 - /usr/local/bin/node
  Yarn: 1.22.19 - /usr/local/bin/yarn
  npm: 10.1.0 - /usr/local/bin/npm
Browsers:
  Chromium: 117.0.5938.62
npmPackages:
  @builder.io/partytown: ^0.8.1 => 0.8.1 
  @builder.io/qwik: ^1.2.12 => 1.2.12 
  @builder.io/qwik-auth: ~0.1.3 => 0.1.3 
  @builder.io/qwik-city: ^1.2.12 => 1.2.12 
  undici: ^5.25.2 => 5.25.2 
  vite: ^4.4.9 => 4.4.9
```

### Additional Information

I created a [Minimal reproducible example](https://stackblitz.com/edit/qwik-starter-deuohs)
add a simple CSS style file in route-head.tsx (/src/components/router-head/route-head.tsx)
add a custom color in tailwind.config.js that used a color variable
use this color text-custom-color1 in index.tsx
but color variable not load: `variable is not defined`

**Comment by nsdonato** [comment] 2023-09-26 08:06
Hey @hosseinitabar how are you? 😊 The problem is that in the colors file https://nbp-perfume.com/colors.css the custom property is --color1, and in the tailwind configuration file you are using --color-1, that's why it doesn't work.

I leave you a fork with the project working, I hope I have helped you: https://stackblitz.com/edit/qwik-starter-xnbop5?file=tailwind.config.js

**Comment by gioboa** [comment] 2023-09-26 16:14
Thanks @nsdonato can we close this issue?

**Comment by nsdonato** [comment] 2023-09-26 16:20
> Thanks @nsdonato can we close this issue?

For me yes @gioboa , I was just waiting if @hosseinitabar confirmed it was that 😊, but I think it could be closed without problem.

**Closed** 2023-09-26 16:25 UTC
Labels: TYPE: bug, STATUS-1: needs triage

**Comment by hosseinitabar** [comment] 2023-09-28 12:18
@nsdonato wow, You are right. It was a mistake on my part. I was involved in complications that I didn't realize this, Thank you
