### ISSUE TITLE
issue with "@builder.io/qwik-city": "0.0.117" 

### ISSUE THREAD

**Issue by gomolsoft** [BuilderIO/qwik#1878] opened 2022-10-25 20:21 UTC
### Qwik Version

0.11.1

### Operating System (or Browser)

all Browsers

### Node Version (if applicable)

16

### Which component is affected?

Qwik City

### Expected Behaviour

I am currently using version "@builder.io/qwik-city": "0.0.112". 
And am trying to upgrade to the latest version, version "@builder.io/qwik-city": "0.0.117". 
`   
 "@builder.io/qwik": "^0.11.1",
 "@builder.io/qwik-city": "^0.0.117",
..
 "vite": "^3.1.8",
..
`

### Actual Behaviour

I get the following error message:

> `
> qwikPlugin.api.getManifest is not a function
> /Volumes/.../node_modules/@builder.io/qwik-city/vite/index.cjs:23909:63
> 23901|    if (r3.paramNames.length > 0) {
> 23902|      const paramNames = JSON.stringify(r3.paramNames);
> 23903|      return [ ${pattern}, ${moduleLoaders}, ${paramNames} ];
>    |              ^
> 23904|    }
> 23905|    return [ ${pattern}, ${moduleLoaders} ];
> `

### Additional Information

the issue can be aswell reproduced in stackblitz
https://stackblitz.com/edit/qwik-starter-h7qjne?file=package.json

**Comment by kwaa** [comment] 2022-10-26 06:10
Duplicate of https://github.com/BuilderIO/qwik/issues/1844 imo

**Comment by gomolsoft** [comment] 2022-10-27 16:52
with the new upddate:
    "@builder.io/qwik": "^0.12.0",
    "@builder.io/qwik-city": "^0.0.118",
is the issue gone.

**Comment by zanettin** [comment] 2022-10-28 18:53
@manucorporat @shairez @adamdbradley could be closed

**Closed** 2022-10-28 23:54 UTC
Labels: bug, triage
