### ISSUE TITLE
Resource remains onPending when running npm run preview

### ISSUE THREAD

**Issue by sdmcallister** [BuilderIO/qwik#1418] opened 2022-09-23 09:38 UTC
### Qwik Version

0.9.0

### Operating System (or Browser)

Chrome / Windows 10

### Node Version (if applicable)

16.14.0

### Which component is affected?

Qwik Runtime

### Expected Behaviour

When using the endpoint `/city`,  the Resource resolves as expected when I run npm run start. In this instance the database information populates the page as expected. I expect this would also occur as well when doing `npm run preview`

I'm mostly following this example and adding the code from mysql2:
https://qwik.builder.io/qwikcity/routing/data/

### Actual Behaviour

When running in preview the endpoint remains onPending when running npm run preview. I didn't see any error messages in the browser. 

### Additional Information

The code is here: https://github.com/sdmcallister/myapi
The database is a recent mysql community and I'm just using the default database `world`.  
Mostly just experimenting and learning about the framework.

**Comment by fotopixel** [comment] 2022-09-23 10:53
same happens also if you use express... for serve. 

if run local with `npm run dev` it work but with `npm run serve ` after adding express via `npm run qwik add express` and build the server and client.

`
export const onGet: RequestHandler<{name: string}> = async () => { 

  const url = `https://api.agify.io/?name=bella`;
  const response = await fetch(url)
  const data = await response.json();
  return data;
};

export default component$(() => {

  const pageData = useEndpoint<{name: string}>();

  return (
    <Resource
      value={pageData}
      onPending={() => <div>Loading...</div>}
      onRejected={() => <div>Error</div>}
      onResolved={(page) => (
        <>
          {page.name}
        </>
      )}
    />
  );
});`

**Comment by strowk** [comment] 2022-09-25 02:34
I had same issue. BTW, this reproduces on official example from here: 
https://qwik.builder.io/tutorial/reactivity/resource/

In `npm run dev` this would show list of repos immediately when page is opened. In preview - no.

**Comment by robert-pitt-foodhub** [comment] 2022-09-25 20:00
I can also confirm this:

*dev:*
<img width="1792" alt="Screenshot 2022-09-25 at 20 55 39" src="https://user-images.githubusercontent.com/70318887/192162697-314dea58-4d1f-431d-b6a7-64f6884d57b4.png">

*preview:*
<img width="1792" alt="Screenshot 2022-09-25 at 20 55 44" src="https://user-images.githubusercontent.com/70318887/192162699-5a1184bf-80c3-43db-8390-a2c5d2a3c7a4.png">

And code setup (typical)
<img width="747" alt="Screenshot 2022-09-25 at 20 57 44" src="https://user-images.githubusercontent.com/70318887/192162804-f16a2dcc-98bc-4d41-a30e-aa8d0fb37a76.png">

Versions:
- `@builder.io/qwik: 0.9.0`
- `@builder.io/qwik-city: 0.0.111`

**Comment by mrkstwrt** [comment] 2022-10-05 14:30
I can confirm this too, works for me when running `npm run dev` however using `npm run serve` or deploying to cloudflare pages and using the adapter causes the above, always stays in the `onPending` state.

**Comment by lukemansell** [comment] 2022-10-05 21:10
If you need a short term fix, removing `onPending={() => <div>Loading...</div>}` seems to make it work.

**Comment by manucorporat** [comment] 2022-10-10 11:30
SHould be fixed in main! next release will include a fix!

**Closed by manucorporat** 2022-10-10 11:30 UTC
Labels: bug, Priority
