### ISSUE TITLE
Create our own benchmark that clearly demonstrates Qwik's strengths

### ISSUE THREAD

**Issue by Evertt** [BuilderIO/qwik#1556] opened 2022-10-02 05:01 UTC
### Is your feature request related to a problem?

After hearing Qwik being explained by the authors on various podcasts, I've become very excited about Qwik and its unique abilities. But for some reason, when I bring it up on Discord servers of other JS frameworks, the response I get is most often that people are very skeptical of the value of Qwik's optimizations.

The main questions I get back are:

1. Is partial hydration not good enough? Is it really necessary to make such granular optimizations?
2. Will the end-user really notice the difference? Or is this just saving milliseconds that the user won't ever notice?

### Describe the solution you'd like

What I think would be cool is to create a web-app of medium complexity built with Qwik (and Qwik City for the SSR of course) and build the exact same web app in at least React with NextJS, Angular with Angular Universal and Vue with NuxtJS. And if you feel like it you could add Solid and Svelte too.

And then write a script that acts as a user, loading the first page, clicking buttons as quickly as they available are to click, following a set path from A to B. I don't know exactly what that app should do exactly nor what the user-path would be, but we can discuss that. I think it should at least include a few routing changes, a form to submit and maybe some animations or lazily loaded stuff that only start working when the user has scrolled them into view.

Maybe run this in a benchmark / e2e test in a Chrome tab that has the network throttled to slow 3G speeds.

And then just let it run and record how long it took for this fake user to get from A to B in all the web apps written in all the different frameworks. I think that way you can really clearly show to users how much faster Qwik is and how noticeable it is.

Would be even better if any person who wants to see this test / benchmark, can just load the page themself and see the script-acting-as-a-user do all the interactions and see how fast the page responds to every input.

### Describe alternatives you've considered

I haven't considered any alternatives. This just seems like the best way to convince anybody of the tangible benefits that Qwik is bringing to the table.

**Comment by Moe03** [comment] 2022-10-02 23:49
I also thought of this when I first knew about qwik, I believe it's insanely powerful than any other framework and has great potential.

The porblem with the current developer trend tho is that they don't care unless there are meaningful reasons in front of them to use a new technology.

Creating an actual production website example built with qwik, react and angular to compare the performance difference would really shine light on why qwik really looks like the future.

All that said, I believe Misko said (in one of his introductory videos about qwik) that builder.io landing page is built both with react and qwik (there are 2 versions) so I guess we already have an example to compare, but I think a more complex example would be better.

**Comment by gioboa** [comment] 2023-12-28 21:35
I close this issue b/c it's a duplicate of https://github.com/BuilderIO/qwik/issues/1404

**Closed by gioboa** 2023-12-28 21:35 UTC
Labels: TYPE: enhancement, STATUS-1: needs triage
