### ISSUE TITLE
[🐞] build scripts stuck after `Built client modules` in node/express adapter

### ISSUE THREAD

**Issue by harshmangalam** [BuilderIO/qwik#5196] opened 2023-09-19 18:43 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

When i run `pnpm run build` in express adapter it stuck after sometime

✓ built in 1.22s
✓ Built client modules

After this cli got stuck

### Reproduction

https://github.com/harshmangalam/qwik-x

### System Info

```shell
System:
    OS: macOS 13.3.1
    CPU: (8) arm64 Apple M1
    Memory: 42.33 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.16.0 - ~/.nvm/versions/node/v18.16.0/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.16.0/bin/yarn
    npm: 9.5.1 - ~/.nvm/versions/node/v18.16.0/bin/npm
    pnpm: 8.6.12 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 116.0.5845.187
    Safari: 16.4
```

**Comment by sirjager** [comment] 2023-09-26 16:47
same here, static adapter: stuck at Built client modules

**Comment by mhevery** [comment] 2023-09-26 20:15
Can I have a reproduction that works on my machine? The current reproduction requires that Postgres DB is running, so I can't reproduce it. 

- [ ]

**Comment by harshmangalam** [comment] 2023-09-26 20:48
@mhevery  do you want `dist` and `server` code ?

**Comment by mhevery** [comment] 2023-09-26 20:53
I need to be able to build it so that I can see how it is failing. So I need a reproduction that is not dependent on installing a DB. I am asking for a simpler reproduction that stands on its own.

**Comment by harshmangalam** [comment] 2023-09-26 20:53
One more thing i noticed that even it is in stuck mode but it generate server bundle and when i manually stop the build process and run  `pnpm run serve` is working fine.

**Comment by harshmangalam** [comment] 2023-09-26 20:54
> I need to be able to build it so that I can see how it is failing. So I need a reproduction that is not dependent on installing a DB. I am asking for a simpler reproduction that stands on its own.

Okay got it

**Comment by harshmangalam** [comment] 2023-09-26 21:15
Actually the problem is  related to drizzle migrator. After commenting the migration code build issues resolved. 
```js

import { drizzle } from "drizzle-orm/postgres-js";
// import { migrate } from "drizzle-orm/postgres-js/migrator";
import postgres from "postgres";
import * as schema from "./schema";
const DRIZZLE_DATABASE_URL = process.env["DRIZZLE_DATABASE_URL"] as string;

if (!DRIZZLE_DATABASE_URL)
  throw new Error("DRIZZLE_DATABASE_URL env variable missing");

// for migrations
// const migrationClient = postgres(DRIZZLE_DATABASE_URL, { max: 1 });
// migrate(drizzle(migrationClient, { schema }), {
//   migrationsFolder: "migrations",
// });

// for query purposes
const queryClient = postgres(DRIZZLE_DATABASE_URL);
export const db = drizzle(queryClient, { schema });

```

**Comment by mhevery** [comment] 2023-09-26 21:48
Great! The importance of having small repros! Can we close this issue?

**Comment by harshmangalam** [comment] 2023-09-26 21:51
Sure you can close it

**Closed** 2023-09-26 22:09 UTC
Labels: TYPE: bug, STATUS-1: needs triage
