### ISSUE TITLE
RequestHanlder type not exported

### ISSUE THREAD

**Issue by chasm** [BuilderIO/qwik#1005] opened 2022-08-10 03:46 UTC
### Qwik Version

0.0.41

### Operating System (or Browser)

macOS 12.5

### Node Version (if applicable)

18.7.0

### Which component is affected?

Qwik City

### Expected Behaviour

I would expect the code to be correct, but although the typecheck passes, I get these warnings:

- Module'"@builder.io/qwik-city"' has no exported member 'RequestHandler'.
- Binding element 'request' (or 'params') implicitly has an 'any' type.

This affects several files. And, indeed, `RequestHandler` is _not_ exported, so why is there an import of it? Strange.

### Actual Behaviour

The app works, but I get a lot of complaints in VSCode because it imports types that have not been exported. Not a showstopper, but annoying and maybe an easy fix?

![Screen Shot 2022-08-10 at 15 39 48](https://user-images.githubusercontent.com/29755/183808551-4b39f561-4240-442b-bcd2-06dfabb72932.png)

**Comment by nnelgxorz** [comment] 2022-08-10 06:28
Hey @chasm! Can you run `npm I @builder.io/qwik-city@latest` and see if that resolves the issue?

It looks like the starters are still set to use a prior version of Qwik City

**Comment by mr-moto** [comment] 2022-08-10 06:36
@chasm @nnelgxorz was having the same issue. can confirm latest version of qwik-city (`v0.0.32`) resolves the issue

**Comment by nnelgxorz** [comment] 2022-08-10 06:48
Thanks for checking @mr-moto! I confirmed locally as well. PR is up to fix. :+1:

**Comment by chasm** [comment] 2022-08-10 06:57
Yes. Upgraded and workin now. Had to restart VSCode. Sorry.

**Comment by nnelgxorz** [comment] 2022-08-10 07:00
@chasm No problem! Thanks for filing the issue so it could get fixed!

**Comment by adamdbradley** [comment] 2022-08-10 11:53
Should be fixed in latest release. Thanks for opening the issue!

**Closed by adamdbradley** 2022-08-10 11:53 UTC
Labels: bug, triage
