### ISSUE TITLE
[🐞] Qwik playground / tutorial broken

### ISSUE THREAD

**Issue by ubarbaxor** [BuilderIO/qwik#3252] opened 2023-03-03 20:41 UTC
### Which component is affected?

Qwik Playground

### Describe the bug

![image](https://user-images.githubusercontent.com/26365493/222823051-40065603-d44e-49f5-9988-6c63365092f7.png)

![image](https://user-images.githubusercontent.com/26365493/222823103-b1c62f02-888c-4a43-955a-02b7175dcd1b.png)
```
Error: Unable to require() path "@builder.io/qwik/build" from a browser environment. at globalThis.qwikServer.globalThis.require (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:33:11) at eval (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:164:20) at eval (eval at g (https://qwik.builder.io/repl/repl-sw.js:1:341), <anonymous>:783:26) at g (https://qwik.builder.io/repl/repl-sw.js:1:377) at async B (https://qwik.builder.io/repl/repl-sw.js:1:1357) at async F (https://qwik.builder.io/repl/repl-sw.js:12:5469)
```

(linked https://github.com/BuilderIO/qwik/issues/1037 for x-ref in case somebody googles around)

### Reproduction

https://qwik.builder.io/tutorial/welcome/overview/

### Steps to reproduce

Just try it 😨 

### System Info

```shell
M1 mac pro / Google Chrome
```

**Comment by zanettin** [comment] 2023-03-03 20:44
Hi @ubarbaxor 👋 
Thanks for creating this issue 🙏  Imo it looks like a duplicate of https://github.com/BuilderIO/qwik/issues/3206. Hope it's okay, when i close this. If not, pls let me know 👼 
Thanks again 😃

**Closed by zanettin** 2023-03-03 20:44 UTC
Labels: bug, triage
