### ISSUE TITLE
[✨] Improve linting to prevent assignement/mutation of a local variable

### ISSUE THREAD

**Issue by FHachez** [BuilderIO/qwik#5120] opened 2023-09-06 20:23 UTC
### Is your feature request related to a problem?

As a person new to Qwik it may be easy to miss that you cannot modify a local variable in a QRL function or even a prop value.

```tsx
import { component$ } from '@builder.io/qwik';

export default component$(() => {
  let localVariable = 'local variable';
  return (
    <>
      <h1>Simple reactivity example!</h1>
      <button onClick$={() => {
        console.log('add data', localVariable)
        localVariable = localVariable + ' - new data'
      }} >greet!</button>
      {localVariable}
    </>
  );
});
```

It's a pretty dumb example. But Qwik won't update the html when the variable is updated. It's not aware that it changed. 
It could be easy to introduce in a more complex function.

## This lead to an error
The code above lead to an error when you click on the button. Here is the generated symbol of the QRL:
<img width="516" alt="image" src="https://github.com/BuilderIO/qwik/assets/3494000/bfe18269-b38a-4453-a0ac-55a214ad8e95">
> Uncaught (in promise) TypeError: Assignment to constant variable.

When Qwik generates the QRL, it uses `const [myVariable] = useLexicalScope()`. Since `myVariable` is a constant, we can't reassign it.

### Describe the solution you'd like

I see two solutions:
- Qwik doesn't fail when we update a local variable.
- Qwik prevents us from making that mistake. I expect that we can catch most of the issues with the eslint.

### Describe alternatives you've considered

-

**Comment by mhevery** [comment] 2023-09-06 21:08
This is a limitation of the playground as it does not run `eslint`. In a real project, `eslint` gives you this error:
![image](https://github.com/BuilderIO/qwik/assets/111951/4b710df6-2726-487d-b612-50ac207eb7db)

So I think this is already working as intended. (Closing as no action on our side)

**Closed by mhevery** 2023-09-06 21:08 UTC
Labels: TYPE: enhancement, STATUS-1: needs triage

**Comment by FHachez** [comment] 2023-09-07 07:34
Nice thanks, I missed it when I tried in vscode.
