### ISSUE TITLE
Why not onClick instead of onClick$ ?

### ISSUE THREAD

**Issue by MattCCC** [BuilderIO/qwik#1936] opened 2022-10-31 19:07 UTC
### Is your feature request related to a problem?

Yes, it disallows for proper transition from React

### Describe the solution you'd like

Use onClick instead of onClick$ without dollar sign

### Describe alternatives you've considered

n/a

**Comment by shairez** [comment] 2022-10-31 19:11
Good question
The $ sign is special in qwik and it what allows it to know where to break the code into lazy loaded chunks

You can find more explanation about it here:
https://qwik.builder.io/docs/advanced/optimizer/

The point of Qwik is not to be 1 to 1 compatible with React, but to be as similar as possible while still innovating with features like resumability.

$ are part of that innovation 

I'm closing this issue as this is not a bug or a feature
but feel free to keep asking follow up questions here or in our discord

**Closed by shairez** 2022-10-31 19:11 UTC
Labels: enhancement, triage

**Comment by KenAKAFrosty** [comment] 2022-11-11 03:36
A dollar sign in the function signature is only one part of the true difference between react and qwik. In fact removing the $ sign to give the surface level appearance of being the same as react would be worse. You could just literally copy + paste react code and get no linting errors buit in reality it's not *actually* that compatible. It's a false sense of security. 

But there's good news!

There are integrations built specifically to help port over from React, properly. See:
https://qwik.builder.io/qwikcity/integrations/react/

You can use things like `qwikify` to help port over React applications piece by piece. Use that kind of tool to get it working in Qwik (but with less benefit than manually converting to a proper Qwik component). 

It works sort of like an island architecture like in Astro where you can have little islands of React components. But also with some tweaks to not always have to hydrate the react component and still have some interactivity. It's pretty wild actually!

**Comment by manucorporat** [comment] 2022-11-11 10:18
Adding some extra docs:

- https://qwik.builder.io/docs/faq/#what-are-all-those-
- https://github.com/BuilderIO/qwik/issues/191
