### ISSUE TITLE
[🐞] onClick$ not always fired

### ISSUE THREAD

**Issue by nelsonprsousa** [BuilderIO/qwik#5982] opened 2024-03-09 02:43 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

When dealing with the `onClick$` event I am expecting that the code is always executed. Looks like there's some racing codition between the default behaviour of anchor's click and the `onClick$` event itself.

### Reproduction

https://github.com/nelsonprsousa/qwik-app-on-click-cookies

### Steps to reproduce

1. Start the app with `yarn start`
2. Open developer tools
3. Click the custom anchor I added to the page
4. The `onClick$` event isn't fired
5. Change the `onClick$` event for the other simple one. There's also a race condition even with this simples use case. Sometimes it is fired, sometimes it isn't.

### System Info

```shell
System:
    OS: Windows 11 10.0.22621
    CPU: (16) x64 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
    Memory: 37.51 GB / 63.72 GB
  Binaries:
    Node: 20.10.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 10.2.3 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.15.4 - C:\Program Files\nodejs\pnpm.CMD
  Browsers:
    Edge: Chromium (122.0.2365.66)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ^1.5.1 => 1.5.1
    @builder.io/qwik-city: ^1.5.1 => 1.5.1
    undici: * => 6.7.1
    vite: ^5.1.4 => 5.1.5
```

**Comment by thejackshelton** [comment] 2024-03-09 07:29
@nelsonprsousa have you tried preventing the default behavior of onClick$ on your a tag?

**Comment by wmertens** [comment] 2024-03-09 07:53
@nelsonprsousa you're triggering a race condition.

Your onclick handler gets called, but since it sometimes has to be downloaded, it can't fire before the browser follows the link.

Instead, you can make your handler a sync$ function (just wrap it with `sync$`, or use a button that looks like a link, or set the cookie at an earlier time.

Closing as everything is working as intended.

**Closed by wmertens** 2024-03-09 07:53 UTC
Labels: TYPE: bug, STATUS-1: needs triage
