### ISSUE TITLE
Serving locally built SSR from the starter app produces an error

### ISSUE THREAD

**Issue by shairez** [BuilderIO/qwik#619] opened 2022-06-14 21:21 UTC
### Qwik Version

0.0.25

### Operating System (or Browser)

Windows / Chrome (incognito)

### Node Version (if applicable)

16.13.0

### Which component is affected?

Starters / CLI

### Expected Behaviour

I expect the binding to work and no error being shown in the console

### Actual Behaviour

STEPS TO REPRODUCE:

1. `npm run build.ssr`
2. `npm run serve`
3. Change the input box value from "world" to "world1"
4. See an error in the console (and no binding happenning = value of world below doesn't change) - 

```
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.

Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://localhost:8080/inlinedQRL
await (async)
b @ (index):26

```

![image](https://user-images.githubusercontent.com/1430726/173691082-1d5a3a88-27b1-4ed6-8649-98a4fcd19592.png)

**Comment by manucorporat** [comment] 2022-06-14 22:20
Duplicate of https://github.com/BuilderIO/qwik/issues/614

We have already identified the source of the bug and we are working on a fix!

**Closed by manucorporat** 2022-06-14 22:20 UTC
Labels: bug

**Comment by shairez** [comment] 2022-06-14 22:51
OK thanks!
Just noting (just in case)  that it's not in QwikCity but in Qwik (but I'm guessing it's the same source of the bug probably)

Thanks for the prompt response @manucorporat !

**Comment by peterboyer** [comment] 2022-07-03 04:14
@shairez I just ran into this same issue.

Looking at the Network tab via my browser's dev tools, when trying to fetch any `q-XXXXXXX.js` file from interacting with the input, the server seems to _fallback_ to returning the <html> of the root route `/` if it can't find the .js in the `dist` folder: which is only created when you run `build` or `build.client`.

So you're probably best of to run `build` to then `serve` to produce both the `server.entry.express.js` code AND the `dist` client-side js fragments that will be dynamically loaded as you interact with the page.
