### ISSUE TITLE
[🐞] useSignal is not updating when I set it inside onResolved

### ISSUE THREAD

**Issue by gustavocadev** [BuilderIO/qwik#4889] opened 2023-07-30 19:01 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug
I'm using Context with a signal and a useResource  in there, I use the context in my component and then

The signal firstAuthor.value is empty even when I've changed it below, which means that is not working, or did I do something wrong?

![image](https://github.com/BuilderIO/qwik/assets/84424661/14c9182b-e2c0-4e68-932a-1d0b37f208ca)
![image](https://github.com/BuilderIO/qwik/assets/84424661/80936c22-60ef-4905-93d2-967ffbfb6a14)
![image](https://github.com/BuilderIO/qwik/assets/84424661/7023ce6b-834f-4e0a-9d4f-00e91175fb8b)

### Reproduction

https://github.com/gustavocadev/repro-case-qwik-1

### Steps to reproduce

`pnpm install` followed by `pnpm dev`

### System Info

```shell
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
    Memory: 5.31 GB / 12.92 GB
  Binaries:
    Node: 18.16.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.6.7 - C:\Program Files\nodejs\npm.CMD
    pnpm: 8.6.5 - ~\AppData\Local\pnpm\pnpm.EXE
  Browsers:
    Edge: Spartan (44.22621.2070.0), Chromium (115.0.1901.188)
    Internet Explorer: 11.0.22621.1
  npmPackages:
    @builder.io/qwik: ^1.2.6 => 1.2.6
    @builder.io/qwik-city: ^1.2.6 => 1.2.6
    undici: 5.22.1 => 5.22.1
    vite: 4.4.0 => 4.4.0
```

**Comment by vinaygosain** [comment] 2023-08-25 08:27
I am facing the same issue. I would like to contribute and fix it if someone can give some pointers and if it seems like a beginner issue .

**Comment by mhevery** [comment] 2023-08-25 17:13
> ### Steps to reproduce
> `pnpm install` followed by `pnpm dev`

Please have empathy for the maintainers and make our life easier by including:
- What do you expect to see? 
- What do you see instead?
- Where do I look to poke on the code?

---

This code is working as intended...

```typescript
export const QuotesProvider = component$(() => {
  const firstAuthor = useSignal('');

  const quotesResource = useResource$(async () => {
    return await server$(async () => {
      const resp = await fetch(
        'https://api.quotable.io/quotes/random?limit=10'
      );
      const quotes = (await resp.json()) as QuotesResponse[];

      // here doesnt work too
      // firstAuthor.value = quotes[0].author;
      return quotes;
    })();
  });

  useContextProvider(QuotesContext, {
    quotesResource,
    firstAuthor,
  });
  return <Slot />;
});
```

in the above code `firstAuthor` is declared in the application, but `firstAuthor.value = quotes[0].author;
` is inside of `server$()`. When you make calls to `server$()`, you get copies of the values, not references. This means that any changes you make to the signals will not be reflected since they are copies. 

I have filed https://github.com/BuilderIO/qwik/issues/5019 to make this foot gun easier to avoid in the future. 

Closing as working as intended.

**Closed by mhevery** 2023-08-25 17:13 UTC
Labels: TYPE: bug, STATUS-1: needs triage

**Comment by vinaygosain** [comment] 2023-08-25 18:24
@mhevery , 
Maybe i missed something, please correct me if i am wrong, but `firstAuthor.value = quotes[0].author;` is not inside of `server$()`, its inside `onResolved` of `<Resource/>` 
Also even we if remove `server$()` altogether from the code and send the fetch call directly, the signal is still not updated when the fetch call is completed and we do not see updated value for `firstAuthor.value` on UI .

**Comment by mhevery** [comment] 2023-08-25 23:20
This is why exact repro instructions are important.

You can't modify signals inside rendering functions. All signal modifications must be done outside of rending, as in handler or task functions.
