### ISSUE TITLE
Dynamic styles are broken:  Internal server error: Qrl($) scope is not a function

### ISSUE THREAD

**Issue by MarkLyck** [BuilderIO/qwik#1728] opened 2022-10-14 01:43 UTC
### Qwik Version

0.11.0

### Operating System (or Browser)

macOS

### Node Version (if applicable)

16.x

### Which component is affected?

Qwik Runtime

### Expected Behaviour

It should parse CSS with variables in the template string.

### Actual Behaviour

When you try to use `useStyles$` or `useStylesScoped$` it fails if you put any variable in the string.

For example this breaks:

```js
const className = "test"
const css = `.${className} { background: red; }`;
useStyles$(css);
```

with the following error:

```error
Qrl($) scope is not a function, but it's capturing local identifiers: className
9:41:56 PM [vite] Internal server error: Qrl($) scope is not a function, but it's capturing local identifiers: className
  Plugin: vite-plugin-qwik
```

Same error happens if I try to make any or all of the CSS string dynamic.

But this runs fine without any issues.
```js
const css = `.test { background: red; }`;
useStyles$(css);
```

The string in the end should be the same.

### Additional Information

Unrelated, but please consider supporting a CSS in JS solution rather than string templates 🙏 They are just all around easier to deal with.

**Comment by wmertens** [comment] 2022-10-23 10:26
Duplicate of #1563 imho

**Comment by manucorporat** [comment] 2022-11-28 14:34
I am closing this issue but keeping this open: https://github.com/BuilderIO/qwik/issues/1728

**Closed by manucorporat** 2022-11-28 14:34 UTC
Labels: bug, triage
