### ISSUE TITLE
[🐞] useContext does not exist

### ISSUE THREAD

**Issue by Dindaleon** [BuilderIO/qwik#2829] opened 2023-02-04 22:56 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

I have been at it for a couple of weeks already and there is no way to solve the issue with `useContext`

Whenever I go from one page to another where I need a context (useContext),  I get the error that the value for useContext() cannot be found:

```
Error: Code(13): Actual value for useContext() can not be found, make sure some ancestor component has set a value using useContextProvider()
```

This functionality is crucial for the app we are developing, I would like to know if there is a ETA for when it is going to be solved so we can decide if we can keep working with Qwik or we need to move to another framework.

### Reproduction

https://stackblitz.com/edit/qwik-starter-cnqpet?file=src%2Froutes%2Fprofile%2Findex.tsx,src%2Fcomponents%2FsomeProvider.tsx,src%2Froot.tsx

### Steps to reproduce

Navigating from Home or Login page to the Profile page where `useContext` is needed, throws the error.

### System Info

```shell
System:
    OS: macOS 13.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 482.52 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 19.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 9.2.0 - /usr/local/bin/npm
  Browsers:
    Brave Browser: 107.1.45.127
    Chrome: 109.0.5414.119
    Edge: 109.0.1518.78
    Safari: 16.1
  npmPackages:
    @builder.io/qwik: 0.17.4 => 0.17.4
    @builder.io/qwik-city: 0.0.128 => 0.0.128
    undici: 5.16.0 => 5.16.0
    vite: 4.0.4 => 4.0.4
```

**Comment by shairez** [comment] 2023-02-05 00:06
duplicate of #2254

**Closed** 2023-02-06 19:37 UTC
Labels: bug, triage
