### ISSUE TITLE
[🐞] useStylesScoped does not apply the "scope" class to anchor tags generated with <Link>

### ISSUE THREAD

**Issue by jmmon** [BuilderIO/qwik#4109] opened 2023-05-08 13:55 UTC
### Which component is affected?

Qwik Optimizer (rust)

### Describe the bug

I'm making a dropdown component utilizing <Link>s, and with `useStylesScoped$` to import the CSS file.

I expected:
- the generated <a> tag to have the special scoped class since it's inside the scoped component

Actually:
- The generated <a> tags inside my component are NOT getting the "scoped styles" class.

Component boundary:
```
<!--qv q:sstyle=⭐️18btke-1 q:id=d q:key=4h7U:H1_0-->
```

How some of the elements inside the component render: (NOTE: the <a> tags are NOT getting the scope class, but the <div> tag DOES get the scope class)
```
<div class="⭐️18btke-1 dropdown" on:mouseenter="/src/dropdown_component_div_onmouseenter_f92gg0ks9dk.js#dropdown_component_div_onMouseEnter_F92gG0kS9dk[0]" on:mouseleave="/src/dropdown_component_div_onmouseleave_rtuofikg19u.js#dropdown_component_div_onMouseLeave_rtuOfikG19U[0]" q:key="5H_1" q:id="e" data-qwik-inspector="components/dropdown/dropdown.tsx:22:7"><!--qv q:id=f q:key=8gdL:5H_0-->
  <a href="/users" preventdefault:click="" class="main link" on:click="/src/dropdown_component_div_link_onclick_kiaqejtaxww.js#dropdown_component_div_Link_onClick_kiAqEJtAxww[0]
/src/link_component_handleclick_event_i1cv0pyjnr0.js#Link_component_handleClick_event_i1Cv0pYJNR0[1 2]" q:key="AD_1" q:id="g">
    <!--qv q:s q:sref=f q:key=--><!--t=h-->Users<!----><!--/qv-->
  </a><!--/qv-->
      
  <div class="⭐️18btke-1 dropdown_menu" data-qwik-inspector="components/dropdown/dropdown.tsx:43:9"><!--qv q:id=i q:key=8gdL:/users/new-->
    <a href="/users/new" preventdefault:click="" class="link" on:click="/src/dropdown_component_div_div_link_onclick_pcnvnzikb6k.js#dropdown_component_div_div_Link_onClick_pCnVnziKB6k[0]
/src/link_component_handleclick_event_i1cv0pyjnr0.js#Link_component_handleClick_event_i1Cv0pYJNR0[1 2]" q:key="AD_1" q:id="j">
      <!--qv q:s q:sref=i q:key=-->New User<!--/qv-->
    </a><!--/qv--><!--qv q:id=k q:key=8gdL:/users/find-->
    
    <a href="/users/find" preventdefault:click="" class="link" on:click="/src/dropdown_component_div_div_link_onclick_pcnvnzikb6k.js#dropdown_component_div_div_Link_onClick_pCnVnziKB6k[0]
/src/link_component_handleclick_event_i1cv0pyjnr0.js#Link_component_handleClick_event_i1Cv0pYJNR0[1 2]" q:key="AD_1" q:id="l">
      <!--qv q:s q:sref=k q:key=-->Find a User<!--/qv-->
    </a><!--/qv-->
    
  </div>
  
</div>
```
**Note the divs DO get the scoped class but the anchors do NOT.**

### This is causing my css rules to not apply properly, e.g.
```
.dropdown.active > .main.link + div.dropdown_menu {
  opacity: 1;
  pointer-events: auto;
}
```

This rule should show the dropdown when the parent container has the class `active` but since this checks the `.main.link` (which is NOT getting the "scoped style" class) this rule never applies properly. Change it to `useStyles$` and it functions properly, since `useStyles$` does not need to add the scoped class to all child elements.

### Reproduction

https://stackblitz.com/edit/qwik-starter-z9kjwp?file=src/components/dropdown/dropdown.tsx

### Steps to reproduce

Use a `useStylesScoped$` inside a component which has a <Link> tag. The generated <a> tag will NOT get the scoped class like it should.

Switch `useStylesScoped$` to `useStyles$` and the styles now apply properly, because there is no need for the scoped class.

### System Info

```shell
System:                                                  
    OS: Windows 10 10.0.19044                              
    CPU: (8) x64 Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz  
    Memory: 4.07 GB / 15.85 GB                             
  Binaries:                                                
    Node: 16.16.0 - C:\Program Files\nodejs\node.EXE       
    Yarn: 3.5.0 - C:\Program Files\nodejs\yarn.CMD         
    npm: 8.11.0 - C:\Program Files\nodejs\npm.CMD   
  Browsers:                                                   
    Edge: Spartan (44.19041.1266.0), Chromium (113.0.1774.35) 
    Internet Explorer: 11.0.19041.1566
```

**Comment by cmbartschat** [comment] 2023-05-08 15:46
Duplicate of https://github.com/BuilderIO/qwik/issues/2071 I think

**Comment by jmmon** [comment] 2023-05-09 00:51
Yes I think it is. Should I close this? 

Even that issue was possibly a duplicate from October. Kinda disappointing this bug has been around a long while... but I hope it can get fixed soon!

**Comment by manucorporat** [comment] 2023-05-14 14:35
the thing is that it's not really a bug. it's how scoping works, every component scoped styles applies only to the component itself.

I think we need better docs about the limitations of useStylesScoped and workarounds.

Notice that other scoping mechanisms that are supported in qwik, such as CSS modules, does not have this problem.

**Closed by manucorporat** 2023-05-14 14:35 UTC
Labels: bug, triage

**Comment by jmmon** [comment] 2023-05-15 03:15
Looks like CSS modules DO in fact have this problem. When targeting a class on a <Link> element with css, it will not apply, because the <Link> is swapped out for an <a> but the scoped class does not get applied properly. If I change the class selector to an `a` element selector, it applies.

https://stackblitz.com/edit/qwik-starter-z9kjwp?file=src%2Fcomponents%2Fdropdown%2Fdropdown.tsx,src%2Fcomponents%2Fdropdown%2Fdropdown.css,src%2Fcomponents%2Fstarter%2Fcounter%2Fcounter.tsx,src%2Fcomponents%2Fstarter%2Fcounter%2Fcounter.module.css

This shows the counter with a <Link class="test"> and when trying to select for `.test` in the CSS module, it fails to apply the style. Swap for an `a` selector and it correctly grabs the <a> tag and applies the style.

And with the useStylesScoped:
A more clear example: every element inside my one single Dropdown component gets the scoped styles class, EXCEPT the anchor generated by the two <Link> tags in the nested <div>:

```
<div class="⭐️18btke-1 dropdown" ...>                          <!-- component outermost element gets the class-->
  <a href="/users" class="⭐️18btke-1 main link" ...>      <!-- regular <a> tag gets the class-->
    <!--t=a-->Users<!---->
  </a>
  <span class="⭐️18btke-1 span" ...>Some span</span>      <!-- span gets the class-->
  <img src="favicon.svg" class="⭐️18btke-1 img" ...>            <!-- img gets the class-->
  <div class="⭐️18btke-1 dropdown_menu" ...>                     <!-- div gets the class-->
    <a href="/users/new" preventdefault:click="" class="link" ...>       <!-- Qwik-City <Link> element does NOT get the class -->
      <!--qv q:s q:sref=b q:key=-->New User<!--/qv-->
    </a>
    <a href="/users/find" preventdefault:click="" class="link" ...>      <!-- Qwik-City <Link> element does NOT get the class -->
      <!--qv q:s q:sref=d q:key=-->Find a User<!--/qv-->
    </a>
  </div>
</div>
```

I think this is indeed a problem with both CSS modules && scoped styles. Neither one seems to work well with <Link> tags. What is the solution to this? I'm out of my league on this but seems like we need to apply the CSS scoping / the module scoping, then render the HTML, and then have the scope class which was created/applied to the <Link> tag carry over to the generated <a> tag?

I mean, I don't remember having these scoping issue when using CSS modules along with React Router <Link> components, in their case the scoped class generated for that element correctly carries over to the underlying <a> tag, right? But for some reason it's not doing the same in Qwik with CSS modules or scoped styles.

**Comment by jmmon** [comment] 2023-05-15 12:51
Attempting to ping @manucorporat just to make sure you see my previous comment. Hope it's more clear! I do think there's a bug - 2 bugs actually: `CSS Modules` && `useStylesScoped` don't work with `<Link>` tags when using CSS `class` selectors to target the elements!)

**Comment by mikeandtherest** [comment] 2023-05-28 21:41
> the thing is that it's not really a bug. it's how scoping works, every component scoped styles applies only to the component itself.
> 
> I think we need better docs about the limitations of useStylesScoped and workarounds.
> 
> Notice that other scoping mechanisms that are supported in qwik, such as CSS modules, does not have this problem.

What you say makes sense, since Link is another (i.e. child) component. However, in so many scenarios we need to be able to style the anchors of a component from the css related to that component, while still sticking to `useStylesScoped$()` to prevent styles leakage. So I don't know if you can get any kind of "helper" for this.
