### ISSUE TITLE
[🐞] firebase: deploy issue

### ISSUE THREAD

**Issue by keenedge** [BuilderIO/qwik#5205] opened 2023-09-22 00:26 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

I followed the instructions from https://qwik.builder.io/docs/deployments/firebase/#deploy-to-firebase

I publish the empty site template to my firebase hosting account.  The site shows up fine on the correct url.

But, (of course there was a but coming)   Some pages to not render if I look in the browser debug console I see some errors of invalid urls for dependencies.  As seen in the attached screen shot

<img width="956" alt="Errors" src="https://github.com/BuilderIO/qwik/assets/531085/2e5d6529-d363-4206-921e-1ee1390a2dd4">

### Reproduction

https://xisle-f85d1.web.app/basic-map/

### Steps to reproduce

npm create qwik@latest
npm install
npm run qwik add leaflet-map
npm run qwik add firebase
npm run build
npm run deploy

### System Info

```shell
Windows 11
```

**Comment by nsdonato** [comment] 2023-09-26 20:35
@keenedge maybe the problem is in firebase configuration, because I try in Vercel and works fine: https://qwik-mn9eklj56-nsdonato.vercel.app/basic-map/

There is an issue related: https://github.com/firebase/quickstart-js/issues/229
https://stackoverflow.com/questions/41144151/firebaseerror-we-are-unable-to-register-the-default-service-worker

I don't know if we should add that configuration in the starter cc @gioboa

**Comment by mhevery** [comment] 2023-09-26 20:42
Can you share a URL of the deployed application so that I can see what is going on?

**Comment by nsdonato** [comment] 2023-09-26 20:48
@mhevery here here is his url in firebase https://xisle-f85d1.web.app/basic-map/ should display this 
![image](https://github.com/BuilderIO/qwik/assets/7875216/3a602205-c4d5-4139-a06b-403d422dc34e)

**Comment by mhevery** [comment] 2023-09-26 20:54
That URL is 404 for me. I need to be able to play with it for me to help.

**Comment by nsdonato** [comment] 2023-09-26 21:09
@mhevery https://react-my-burger-a8bf9.web.app/basic-map/

![image](https://github.com/BuilderIO/qwik/assets/7875216/45fb3e56-ad33-4abe-b1f6-c724c9ae0a7a)

**Comment by mhevery** [comment] 2023-09-26 21:47
So it seems like https://react-my-burger-a8bf9.web.app/service-worker.js is 404. Maybe your firebase is misconfigured to serve that? Can you share your firebase config file?

**Comment by nsdonato** [comment] 2023-09-26 22:05
I didn't configure anything extra from Firebase, I just followed the steps of the person who had this problem to try to reproduce it.

If anything extra needs to be configured I honestly have no idea 😅
Repo: https://github.com/nsdonato/issue-5205

Maybe he needs to configure this?: https://documentation.mapp.com/1.0/en/step-1-configuration-firebase-and-service-worker-19129487.html 

Should we add documentation about it here?? https://qwik.builder.io/docs/deployments/firebase/ 

The "strange" thing is that in vercel no other configuration is necessary.

**Comment by mhevery** [comment] 2023-09-26 22:23
> Maybe he needs to configure this?: https://documentation.mapp.com/1.0/en/step-1-configuration-firebase-and-service-worker-19129487.html

That is a firebase worker, not ours; that is not applicable here.

The project works fine in local emulation, so that is weird....

I tried to deploy it to firebase, but it requires a paid account. Are you using some features that require that? I thought a free tier should be enough.

**Comment by mhevery** [comment] 2023-09-26 22:27
This seems related https://discord.com/channels/842438759945601056/1154461381068853308/1155658753983660072

**Comment by nsdonato** [comment] 2023-09-26 22:33
I also thought that the free one was enough, but when I followed the steps it warned me in the console that it was pay to go, and I put the card "for the cause" 😅 anyway it's free until you use one or another feature.

The thread on discord for sure is the answer to this problem! you need to try it @keenedge

**Comment by mhevery** [comment] 2023-09-26 22:34
What needs to be changed in the starter? (and any chance, could you send a PR, please?)

**Comment by mhevery** [comment] 2023-09-26 22:37
I assume this file needs to be updated: https://github.com/BuilderIO/qwik/blob/main/starters/adapters/firebase/firebase.json

**Comment by gioboa** [comment] 2023-09-27 05:58
@mhevery and @nsdonato great investigation. 👏
I merged the related PR and I close this issue.
@keenedge thanks to report this problem.

**Closed by gioboa** 2023-09-27 05:58 UTC
Labels: TYPE: bug, COMMUNITY:  good first issue, STATUS-1: needs triage
