### ISSUE TITLE
[🐞] SSG (vercel edge) using node dependencies

### ISSUE THREAD

**Issue by JoepKockelkorn** [BuilderIO/qwik#5714] opened 2024-01-15 07:58 UTC
### Which component is affected?

Qwik Rollup / Vite plugin

### Describe the bug

I'm using Qwik with the Vercel Edge adapter and basically all my routes are now being generated using SSG. Now, I want to use a library that has a node dependency during the SSG process, but the vercel edge adapter throws an error during the build because it uses `ssr.noExternal: true` as a hardcoded value.

The error:
```
[commonjs--resolver] Cannot bundle Node.js built-in "stream" imported from "node_modules/reading-time/lib/stream.js". Consider disabling ssr.noExternal or remove the built-in dependency.
file: /Users/joepkockelkorn/Repos/Personal/joepkockelkorn.com/node_modules/reading-time/index.js
error during build:
RollupError: Cannot bundle Node.js built-in "stream" imported from "node_modules/reading-time/lib/stream.js". Consider disabling ssr.noExternal or remove the built-in dependency.
    at error (file:///Users/joepkockelkorn/Repos/Personal/joepkockelkorn.com/node_modules/rollup/dist/es/shared/parseAst.js:337:30)
    at Object.error (file:///Users/joepkockelkorn/Repos/Personal/joepkockelkorn.com/node_modules/rollup/dist/es/shared/node-entry.js:18485:20)
    at Object.resolveId (file:///Users/joepkockelkorn/Repos/Personal/joepkockelkorn.com/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:28991:34)
    at Object.handler (file:///Users/joepkockelkorn/Repos/Personal/joepkockelkorn.com/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:67380:19)
    at file:///Users/joepkockelkorn/Repos/Personal/joepkockelkorn.com/node_modules/rollup/dist/es/shared/node-entry.js:18670:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///Users/joepkockelkorn/Repos/Personal/joepkockelkorn.com/node_modules/rollup/dist/es/shared/node-entry.js:18570:28)
    at async resolveId (file:///Users/joepkockelkorn/Repos/Personal/joepkockelkorn.com/node_modules/rollup/dist/es/shared/node-entry.js:17239:26)
    at async ModuleLoader.resolveId (file:///Users/joepkockelkorn/Repos/Personal/joepkockelkorn.com/node_modules/rollup/dist/es/shared/node-entry.js:17653:15)
    at async file:///Users/joepkockelkorn/Repos/Personal/joepkockelkorn.com/node_modules/vite/dist/node/chunks/dep-V3BH7oO1.js:8338:16
    at async Promise.all (index 1)
```

I applied a sub-optimal workaround by defining resolve aliases, so vite is happy. SSG still works as expected, not sure if that is actually using the node dependencies or the applied aliases. For this workaround, [see the main branch](https://github.com/JoepKockelkorn/joepkockelkorn.com/blob/main/adapters/vercel-edge/vite.config.ts#L14).

Is there a better workaround than specifying `resolve.alias`, or should the vercel edge adapter have additional options?

### Reproduction

https://github.com/JoepKockelkorn/joepkockelkorn.com/tree/ssg-node-deps

### Steps to reproduce

- Use the specified node version (`.nvmrc`)
- `npm i`
- `npm run build`

### System Info

```shell
System:
    OS: macOS 14.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 518.92 MB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.11.0 - ~/Library/Caches/fnm_multishells/59371_1705267073843/bin/node
    npm: 10.2.4 - ~/Library/Caches/fnm_multishells/59371_1705267073843/bin/npm
    pnpm: 7.29.2 - /usr/local/bin/pnpm
    Watchman: 2023.04.17.00 - /usr/local/bin/watchman
  Browsers:
    Chrome: 120.0.6099.216
    Safari: 17.2.1
  npmPackages:
    @builder.io/partytown: ^0.8.2 => 0.8.2
    @builder.io/qwik: ^1.3.5 => 1.3.5
    @builder.io/qwik-city: ^1.3.5 => 1.3.5
    undici: 5.28.2 => 5.28.2
    vite: 5.0.11 => 5.0.11
```

**Comment by wmertens** [comment] 2024-01-15 08:01
Doesn't vercel edge mean that you cannot use any binary node dependencies? So you can't use the reading-time module, and everything needs to be bundled into the ssr script.

You could try to fork it and make it use web streams which are available?

**Comment by JoepKockelkorn** [comment] 2024-01-15 08:10
> Doesn't vercel edge mean that you cannot use any binary node dependencies? So you can't use the reading-time module, and everything needs to be bundled into the ssr script.
> 
> You could try to fork it and make it use web streams which are available?

I'm aware it uses a different runtime than node, but all my routes are being SSG'd so node is actually unused at runtime. So I actually don't want any streams to be used, not node, not web 😄. But that might be hard/impossible for the plugin to detect.

The vercel edge runtime [does actually support some node APIs](https://vercel.com/docs/functions/edge-functions/edge-runtime), so I think there should be some escape hatch to tell vite/qwik to ignore some node APIs. `ssr.noExternal: true` seems a bit too strict imo.

**Comment by wmertens** [comment] 2024-01-15 10:14
Well, a PR for better Vercel buils is very welcome :-)

So all your pages are SSG and SSR never runs on vercel, you're just supporting server$ calls or what?

I suppose the build process for SSG could detect if it's used, then build the preview build instead, and run SSG with that. And then a flag to disable SSR in the vercel build?

**Comment by JoepKockelkorn** [comment] 2024-01-15 10:25
> So all your pages are SSG and SSR never runs on vercel, you're just supporting server$ calls or what?

The use case for SSR in my app isn't there **yet**. Sure I can build it with Astro or other SSG-capable frameworks but I just love the mental model of Qwik and want to gain experience and confidence with it so I can vouch for it, because I think it's the future.

I'm not sure I understand which changes are needed for my unique use case to create a PR. But if I would understand I'd be happy to 😃.

**Comment by wmertens** [comment] 2024-01-15 10:29
Ok so the problem is that you're importing something that Vite can't bundle for a js-only environment.
Easiest change is to not import that (your code), or change the noExternals to a list of allowed externals matching what vercel supports (a PR).

What I proposed was not such a great idea, namely that if the module is only needed in SSR and you're not doing SSR, then another build can do the SSR (a way more complex PR).

**Comment by wmertens** [comment] 2024-01-17 15:16
I'm going to close this in favor of #5717, the general issue is that the current vercel integration is too strict about externals. It would be great if someone can find the best way to build for Vercel, their documentation about Vite is here: https://vercel.com/docs/frameworks/vite

**Closed by wmertens** 2024-01-17 15:16 UTC
Labels: TYPE: bug, STATUS-1: needs triage
