### ISSUE TITLE
Build error after adding express adaptor

### ISSUE THREAD

**Issue by szilagyi-sandor** [BuilderIO/qwik#2048] opened 2022-11-08 12:51 UTC
### Qwik Version

0.12.1

### Operating System (or Browser)

Chrome

### Node Version (if applicable)

v16.15.1

### Which component is affected?

Qwik City

### Expected Behaviour

After adding the express server adaptor via "npm run qwik add" building the project should be successful.

### Actual Behaviour

The build fails with the follwing error:
error during build:
Error [PLUGIN_ERROR]: Only URLs with a scheme in: file, data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'c:'
    at new NodeError (node:internal/errors:372:5)
    at throwIfUnsupportedURLScheme (node:internal/modules/esm/resolve:1120:11)
    at defaultResolve (node:internal/modules/esm/resolve:1200:3)
    at ESMLoader.resolve (node:internal/modules/esm/loader:580:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:294:18)
    at ESMLoader.import (node:internal/modules/esm/loader:380:22)
    at importModuleDynamically (node:internal/modules/esm/translators:106:35)
    at importModuleDynamicallyCallback (node:internal/process/esm_loader:35:14)

**Comment by manucorporat** [comment] 2022-11-08 15:31
Can you test with `npm create qwik@0.13.0-dev20221108030156`? i think it's already fixed

**Comment by szilagyi-sandor** [comment] 2022-11-08 16:32
> Can you test with `npm create qwik@0.13.0-dev20221108030156`? i think it's already fixed

Same error, unfortunately.

**Comment by manucorporat** [comment] 2022-11-08 18:40
Unfortunately, i dont have a windows machine to reproduce or debug this issue :/

**Comment by zanettin** [comment] 2022-11-13 21:49
@szilagyi-sandor did you have the chance to check it on the latest version of qwik (`0.13.3`) and qwik-city (`0.0.122`)?

**Comment by manucorporat** [comment] 2022-12-04 11:52
Closing since this issue should be fixed!

**Closed by manucorporat** 2022-12-04 11:52 UTC
Labels: bug, triage
