### ISSUE TITLE
[🐞] Failing output on Vercel Edge deployment

### ISSUE THREAD

**Issue by flaming-codes** [BuilderIO/qwik#5789] opened 2024-01-27 20:24 UTC
### Which component is affected?

Qwik City (routing)

### Describe the bug

When triggering a new deployment for a Qwik City project hosted on Vercel w/ the Vercel Edge adapter, the process completes until the final step `Deploying Outputs`. This then fails with the following error message:

```
Error: The Edge Function "_qwik-city" is referencing unsupported modules:
	- __vc__ns__/0/entry.vercel-edge.js: /vercel/path1/.vercel/output/functions/_qwik-city.func/@qwik-city-not-found-paths.js, /vercel/path1/.vercel/output/functions/_qwik-city.func/@qwik-city-static-paths.js
```

I encountered this issue after upgrading my dependencies (therefore using the latest Qwik + City versions). 

The odd thing is, after downgrading to the latest stable version of project regarding the deployment, the build deployment output error still happens.

My last working deployment was on 24-01-2024 [(snapshot)](https://github.com/flaming-codes/flaming-codes-web/tree/fb1c650a07f426960b92797b463f4602fe60e6df). When comparing against the failing state, you can see that there are no differences [(diff)](https://github.com/flaming-codes/flaming-codes-web/compare/fb1c650a07f426960b92797b463f4602fe60e6df). 

### Reproduction

https://github.com/flaming-codes/flaming-codes-web

### Steps to reproduce

Deploy project on Vercel.
<img width="1350" alt="Screenshot 2024-01-27 at 21 23 24" src="https://github.com/BuilderIO/qwik/assets/11635736/3c570a80-3650-42f1-95d3-f2291ca01d60">

### System Info

```shell
System:
    OS: macOS 14.3
    CPU: (10) arm64 Apple M1 Pro
    Memory: 247.84 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.10.0 - ~/.nvm/versions/node/v20.10.0/bin/node
    npm: 10.2.3 - ~/.nvm/versions/node/v20.10.0/bin/npm
    bun: 0.1.4 - ~/.bun/bin/bun
  Browsers:
    Chrome: 116.0.5845.179
    Edge: 121.0.2277.83
    Firefox Nightly: 117.0a1
    Safari: 17.3
  npmPackages:
    @builder.io/qwik: ^1.4.0 => 1.4.2 
    @builder.io/qwik-city: ^1.4.0 => 1.4.2 
    undici: ^5.26.0 => 5.28.2 
    vite: ^5.0.11 => 5.0.12
```

**Comment by wmertens** [comment] 2024-01-28 09:25
Duplicate of #5774, fix incoming

**Closed** 2024-01-30 22:38 UTC
Labels: TYPE: bug, STATUS-1: needs triage
