### ISSUE TITLE
[🐞] Qwik City Form trigger routeLoader$

### ISSUE THREAD

**Issue by mhuretski** [BuilderIO/qwik#5086] opened 2023-09-01 22:18 UTC
### Which component is affected?

Qwik City (routing)

### Describe the bug

Each time qwik city `Form` is submitted `routeLoader$` is triggered.

### Reproduction

https://stackblitz.com/edit/qwik-starter-ejtnij?file=src%2Froutes%2Flayout.tsx

### Steps to reproduce

```
import { component$ } from '@builder.io/qwik';
import { routeLoader$, Form } from '@builder.io/qwik-city';

export const useServerTimeLoader = routeLoader$(async () => {
  console.log('triggered');
});

export default component$(() => {
  return (
    <Form class="m-4 flex items-center">
      <button type="submit" class="mx-4 h-[52px] items-center">
        Use Action Test
      </button>
    </Form>
  );
});
```

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: 1.2.7 => 1.2.7 
    @builder.io/qwik-city: 1.2.7 => 1.2.7 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

**Comment by mhevery** [comment] 2023-09-05 18:46
Yes, that works as intended. This is so that the loaders can load new data as a result of the action. In the future we plan to have ways to "cache" loaders, but for now the re-run....

Closing as working as intended...

**Comment by mhuretski** [comment] 2023-09-05 19:39
@mhevery, thank you for explanation

`server$`, `routeAction$`, `globalAction$` trigger `routeLoader$`. 
Is there any way to send an action and get the response without any side effects? Or any other built-in primitive to use?

I'm building qwik micro-fronted web app and mfes don't understand how to use data from loaders when we're on the client, so for this setup data from server is useless but takes time to execute. I have to notify required parts of the app via custom events anyway.

The only solution I see is not to use `routeAction$`, `globalAction$` or `server$` if I want to avoid unneeded executions and to create some custom api endpoints and call them via `fetch`. The problem is DX feels very rough, mfes don't work with SPA and I can't use primitives for communication with server. In theory mfes allow to build extremely complex and performant systems but required development effort seems to be quite high to accomplish this goal compared to other suboptimal solutions.

**Comment by mhevery** [comment] 2023-09-05 19:57
> `server$`, `routeAction$`, `globalAction$` trigger `routeLoader$`.
> Is there any way to send an action and get the response without any side effects? Or any other built-in primitive to use?

as of right now no. This is because actions can run without client-side JS, as in submitting a form. In which case the server just re-renders the whole page and re-executes everything. So with JS on we emulate that behavior. 

> I'm building qwik micro-fronted web app and mfes don't understand how to use data from loaders when we're on the client, so for this setup data from server is useless but takes time to execute. I have to notify required parts of the app via custom events anyway.

Have you seen our MFE demo: https://github.com/gioboa/qwik-dream-demo



> The only solution I see is not to use `routeAction$`, `globalAction$` or `server$` if I want to avoid unneeded executions and to create some custom api endpoints and call them via `fetch`. The problem is DX feels very rough, mfes don't work with SPA and I can't use primitives for communication with server. In theory mfes allow to build extremely complex and performant systems but required development effort seems to be quite high to accomplish this goal compared to other suboptimal solutions.

Consider using `server$` which has very clean/simple ergonomics...


I am going to close this issue as working as intended. Feel free to create more specific issues to keep the discussion going.

**Closed by mhevery** 2023-09-05 19:57 UTC
Labels: TYPE: bug, STATUS-1: needs triage
