### ISSUE TITLE
[🐞] Splatting/Spreading event without $ handlers breaks the optimizer

### ISSUE THREAD

**Issue by gabrielgrant** [BuilderIO/qwik#5540] opened 2023-12-07 19:32 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

Edit: see comment below -- this was actually a missing $

---

Trying to splat an event handler prop seems to cause the optimizer to barf

```
export default component$(() => {
  const splatProps = {
    onClick$: () => console.log('hello'),
  };
  return <button {...splatProps}>Hello Qwik</button>;
});
````

```
Error: `line` must be greater than 0 (lines start at line 1)
    at originalPositionFor$1 (/home/projects/qwik-starter-a8jwk5/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:10169:19)
    at eval (/home/projects/qwik-starter-a8jwk5/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55782:25)
    at eval (/home/projects/qwik-starter-a8jwk5/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55773:21)
    at ssrRewriteStacktrace (/home/projects/qwik-starter-a8jwk5/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55772:10)
    at ssrFixStacktrace (/home/projects/qwik-starter-a8jwk5/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:55825:24)
    at Object.ssrFixStacktrace (/home/projects/qwik-starter-a8jwk5/node_modules/vite/dist/node/chunks/dep-3b8eb186.js:65006:13)
    at eval (/home/projects/qwik-starter-a8jwk5/node_modules/@builder.io/qwik/optimizer.cjs:2897:18)
```

### Reproduction

https://stackblitz.com/edit/qwik-starter-a8jwk5?file=src%2Froutes%2Findex.tsx

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 18.18.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.10.5 - /usr/local/bin/pnpm
  npmPackages:
    @builder.io/qwik: ^1.2.11 => 1.2.11 
    @builder.io/qwik-city: ^1.2.11 => 1.2.11 
    undici: 5.22.1 => 5.22.1 
    vite: 4.4.7 => 4.4.7
```

### Additional Information

Splatting non event handler props seems to work fine: https://stackblitz.com/edit/qwik-starter-ysyan7?file=src%2Froutes%2Findex.tsx

This is needed to add Qwik support to Zag: https://zagjs.com/overview/faq#what-would-it-take-to-support-other-frameworks

Similar to #3926

**Comment by gabrielgrant** [comment] 2023-12-08 04:08
Seems this problem was actually just caused by not wrapping the function in a `$`: https://stackblitz.com/edit/qwik-starter-vwdyrq?file=src%2Froutes%2Findex.tsx

This is already noted in the docs: https://qwik.builder.io/docs/components/events/#reusing-event-handlers

Would be great if the error were a little less opaque

**Comment by wmertens** [comment] 2024-01-19 14:47
I'm going to close this as it's working as intended. You can see the diagnostics outputting the correct error in this playground https://qwik.builder.io/playground/#v=1.1.5&f=Q0o0RsbG2BKNDrzK1VGAcMAlG8VpCVb55ySCEnVBMTB4QMIK8PrUChpcyNW4egYoLNQ1dYAqga5HpEhIo0ShWk9PD2FkLUrQQdsto2l1qKZVAA

**Closed** 2024-01-19 14:47 UTC
Labels: TYPE: bug, STATUS-1: needs triage
