### ISSUE TITLE
[Bug] scss with Qwik starter and ssr is broken

### ISSUE THREAD

**Issue by gioboa** [BuilderIO/qwik#749] opened 2022-07-12 07:19 UTC
### Qwik Version

v0.0.34

### Operating System (or Browser)

macOs + Chrome

### Which component is affected?

Qwik Rollup / Vite plugin

### Expected Behaviour

scss styles loaded correctly 

### Actual Behaviour

1. `npm init qwik@latest`
2. Choose Starter, Express and add Prettier
3. `cd qwik-app`
4. `npm install`
5. `npm install sass` <-- UPDATE
6. add .mytitle { color: red; } inside global.css
7. add `mytitle` class to h1 selector inside `app.tsx`
8. rename global.css to global.scss
9. fix global.css import inside root.tsx
10. run `npm run dev.ssr` and `mytitle` class is not loaded

### Additional Information

With `npm run dev` is working correctly

**Comment by nnelgxorz** [comment] 2022-07-12 18:35
Glenn from Discord here. :wave: 

Looks like this might be a [vite thing](https://vitejs.dev/guide/features.html#css-pre-processors)?

Does running `npm add -D sass` help?

**Comment by nnelgxorz** [comment] 2022-07-12 18:45
Ah. Got it work by running that command and import the styles in my layout instead of the root.tsx and using useStyles$ inside of the layout component.

```
import { component$, useStyles$ } from '@builder.io/qwik';
import styles from "../global.scss"

export default component$(() => {
  useStyles$(styles);
  return ...
});
```

**Comment by gioboa** [comment] 2022-07-12 18:47
sorry, I miss to report this step. I did also `npm install sass` after step number 4 
I will update the main message

**Comment by gioboa** [comment] 2022-07-12 19:00
Yep, I added useStyle directly inside my App component and now works correctly
```
....
import styles from '../../global.scss';

export const App = component$(() => {
	useStyles$(styles);
        ....
});
```
is it the right way to manage scss inside Qwik?

**Comment by nnelgxorz** [comment] 2022-07-12 19:26
I don't think it's the right way. It's not the wrong way either. Loading from the root.tsx should work, so I'm pretty sure this bug or something that should be documented if it's not. 

But at least we found a work-around so you can keep working. :+1:

**Comment by manucorporat** [comment] 2022-07-14 07:36
It's also a vite thing, but when using `useStyle$()` it's good to import css or scss using `?inline` like this:
```
import styles from '../../global.scss?inline';

export const App = component$(() => {
	useStyles$(styles);
        ....
})
```

Otherwise vite will generate global styles, and extra .css files, in effect loading the css twice. 
Not very happy with this... but i cant find a better way in Vite yet

**Comment by omarbelkhodja** [comment] 2022-11-09 17:37
I'm facing a similar issue, and it is randomly happening... I'm trying to import bootstrap files inside my own .scss file. Sometimes an error is raised `[plugin:vite:css] [sass] Undefined variable`. You have to refresh a few times to see this error happen, as if imported .scss files are not loaded in the correct order. I'm able to reproduce in the following [stackblitz](https://stackblitz.com/edit/qwik-starter-b9verj?file=src%2Fcomponents%2Fbutton%2Fbutton.scssl)

**Comment by manucorporat** [comment] 2022-11-20 11:37
is this still a problem with latest?

**Comment by omarbelkhodja** [comment] 2022-11-21 12:20
> is this still a problem with latest?

I have upgraded all my project dependencies to latest versions, including latest from qwik and from vitejs. I don't see any issue anymore. Thanks !

**Comment by zanettin** [comment] 2022-11-24 21:53
@omarbelkhodja nice! would you mind to close the issue? 🙏

**Comment by omarbelkhodja** [comment] 2022-11-28 14:23
Sorry guys... The issue appeared again. It is very random. It is like it worked without any problem during a few days, then it reappeared again. Sometimes, it is like no problem during the first startup, but when hot reload happens, the issue appears.

**Comment by manucorporat** [comment] 2022-12-04 11:38
The new issues is probably different and worths a new issue reproduction! i am gonna close this issue, but we should open a new one with a new repo case if in some cases it does not work.

**Closed by manucorporat** 2022-12-04 11:38 UTC
Labels: bug
