### ISSUE TITLE
[🐞] Error is off by one line

### ISSUE THREAD

**Issue by mhevery** [BuilderIO/qwik#2528] opened 2022-12-28 19:14 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

Error description has wrong line number.

```
tweetURL is not defined
/Users/misko/work/repos/qwik-twitter/src/routes/tweet/[tweetId]/tweet.tsx:496:15
493|  export const CreatedAt = (props: { tweet: TweetJsonResponse }) => {
494|    return (
495|      <div class="tweet-time">
   |                  ^
496|        <a href={tweetURL} target="_blank" rel="noreferrer noopener">
497|          {formatDate(props.tweet.data.created_at)}
    at CreatedAt (/Users/misko/work/repos/qwik-twitter/src/routes/tweet/[tweetId]/tweet.tsx:496:15)
    at invoke (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:706:26)
    at renderNode (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:7287:17)
    at processData (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:7298:16)
    at file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:7360:26
    at Array.reduce (<anonymous>)
    at walkChildren (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:7345:21)
    at processData (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:7301:16)
    at renderNode (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:7246:25)
    at processData (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:7298:16)
    at walkChildren (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:7335:16)
    at renderNodeVirtual (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:6887:21)
    at file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:6991:16
    at async renderRoot (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:6826:5)
    at async renderSSR (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/core.mjs:6822:5)
    at async renderToStream (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/server.mjs:632:3)
    at async Proxy.renderToString (file:///Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik/server.mjs:724:18)
    at async onGet (/Users/misko/work/repos/qwik-twitter/src/routes/tweet/[tweetId]/index.tsx:19:23)
    at async Object.next (/Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik-city/vite/index.cjs:22511:9)
    at async runNext (/Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik-city/vite/index.cjs:22679:5)
    at async /Users/misko/work/repos/qwik-twitter/node_modules/@builder.io/qwik-city/vite/index.cjs:23059:11
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.

```

### Reproduction

https://stackblitz.com/edit/qwik-starter-3bqyzv?file=README.md,src%2Froutes%2Findex.tsx

### Steps to reproduce

Fail to build a minimal reproduction. Will update once I have more info.

### System Info

```shell
"@builder.io/qwik": "0.16.1",
    "@builder.io/qwik-city": "^0.1.0-beta6",
```
```


### Additional Information

_No response_

**Comment by manucorporat** [comment] 2022-12-29 16:27
In the provided repo case, i cant reproduce it:
<img width="1706" alt="Screenshot 2022-12-29 at 17 27 10" src="https://user-images.githubusercontent.com/127379/209981467-a511479d-d50d-4447-b39d-e2b71188c023.png">

**Comment by manucorporat** [comment] 2023-02-13 11:34
Should be fixed now!

**Closed by manucorporat** 2023-02-13 11:34 UTC
Labels: bug, triage
