### ISSUE TITLE
useStylesScoped$ not working with interpolated strings

### ISSUE THREAD

**Issue by ValiDraganescu** [BuilderIO/qwik#1781] opened 2022-10-18 15:04 UTC
### Qwik Version

v0.11.0

### Operating System (or Browser)

macOS (Brave, Chrome)

### Node Version (if applicable)

16.13.0

### Which component is affected?

Qwik Optimizer (rust)

### Expected Behaviour

The program should compile correctly when using interpolated strings

### Actual Behaviour

The program throws an error
```
 [vite] Internal server error: Qrl($) scope is not a function, but it's capturing local identifiers: elevation
```

### Additional Information

Some context for debugging: I created a simple component like this

```
export const Button = component$() => {

    const theme = useContext(ThemeContext);

    const radius = 4;
    cons title = 'test';

    useStylesScoped$(`
    .button {
      corner-radius: ${radius}px;
    }
    `);


    return <>
        <button
            class={mergeClasses('button', classes)}
            style={buttonStyle}
            preventdefault:click
        >
            {title}
        </button>
    </>;
});
```

However, this one works
```
export const Button = component$() => {

    const theme = useContext(ThemeContext);
    cons title = 'test';

    useStylesScoped$(`
    .button {
      corner-radius: 4px;
    }
    `);


    return <>
        <button
            class={mergeClasses('button', classes)}
            style={buttonStyle}
            preventdefault:click
        >
            {title}
        </button>
    </>;
});
```
So it must have to do with the fact that the `radius` variable is interpolated

**Comment by wmertens** [comment] 2022-10-23 10:26
Duplicate of #1728 and generally a duplicate of #1563

**Comment by manucorporat** [comment] 2022-11-28 14:35
Dynamic useStylesScope$() is very tricky and not its intended use case... i will leave this issue open, in the meantime we need to extend the docs to better explain this API

**Comment by wmertens** [comment] 2022-11-28 15:34
In [#1563](https://github.com/BuilderIO/qwik/issues/1563#issuecomment-1313866624) I explain how to achieve dynamic styles, but I think that between build-time support like Vanilla-Extract and CSS Variables support, there's very little reason to have dynamic styles (except for DX and supporting old styling systems).

**Comment by zanettin** [comment] 2023-03-05 19:45
I'll close this issue on favor of #1728 and #1563. Thanks for creating this one @ValiDraganescu 🙏

**Closed by zanettin** 2023-03-05 19:45 UTC
Labels: bug, triage
