### ISSUE TITLE
[🐞] Cannot have 2+ Playground tabs open at the same trime

### ISSUE THREAD

**Issue by samijaber** [BuilderIO/qwik#2680] opened 2023-01-20 16:07 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

- Open more than 1 playground tab
- All tabs after the 1st one will have infinite spinners

### Reproduction

https://qwik.builder.io/playground

### System Info

```shell
n/a
```

### Additional Information

Likely related to #2169

**Comment by zanettin** [comment] 2023-02-11 12:16
Hi @samijaber 👋 thank you for creating this issue! looks for me like a duplicate of https://github.com/BuilderIO/qwik/issues/2169, right?

**Closed** 2023-02-23 12:37 UTC
Labels: bug, triage
