### ISSUE TITLE
[🐞] Catch routing is not same as before after v1.2.8

### ISSUE THREAD

**Issue by saeedhbi** [BuilderIO/qwik#5049] opened 2023-08-29 14:12 UTC
### Which component is affected?

Qwik City (routing)

### Describe the bug

I do have localized routing which all routes are behind a `[...lang]` route. Until **v1.2.7** it worked properly and all routes served behind this param route, but after this version, it's not working and only the `index.tsx` file is serving.

I have to use this approach now and the project is big to refactor this large scope. I'm not sure if this is a bug or a change but I didn't find any related migration for it.

@robisim74 Do you have any idea? I'm using `qwik-speak` for localization. But in this reproduction URL, I'm not even using the package and the problem is appearing.

### Reproduction

https://stackblitz.com/edit/qwik-starter-pgr8rp

### Steps to reproduce

- npm run build
- npm run serve

### System Info

```shell
System:
    OS: Linux 5.0 undefined
    CPU: (4) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.20.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 9.4.2 - /usr/local/bin/npm
    pnpm: 8.6.10 - /usr/local/bin/pnpm
```

**Comment by gioboa** [comment] 2023-08-29 14:22
Hi @saeedhbi thanks for the report. which are the steps to reproduce the problem?
If the issue is with `qwik-speak` I think is correct to open the issue in qwik-speak repository.

**Comment by robisim74** [comment] 2023-08-29 14:27
@gioboa Optional params like` [...lang]` are [Qwik feature](https://qwik.builder.io/docs/routing/#directory-based-routing), not `qwik-speak` feature

**Comment by saeedhbi** [comment] 2023-08-29 14:30
> Hi @saeedhbi thanks for the report. which are the steps to reproduce the problem? If the issue is with `qwik-speak` I think is correct to open the issue in qwik-speak repository.

The problem is in the reproduction URL which is using v1.2.9 now. But, by changing the version of Qwik libraries to v1.2.7, it will work.

I replied to @robisim74 because this feature of Qwik (optional params) is used in his library and I want to know his idea.

**Comment by mhevery** [comment] 2023-08-29 15:59
Fixed in https://github.com/BuilderIO/qwik/pull/5004 and should have been working in 1.2.9

**Comment by robisim74** [comment] 2023-08-29 16:14
Hi @mhevery , unfortunately it is no longer working also in versions 1.2.9 and 1.2.10

**Comment by mhevery** [comment] 2023-08-29 17:15
So your route is `src/routes/[...lang]/demo/flowers/`... But that is wrong. The correct route should be `src/routes/[lang]/demo/flowers/`. The `[...lang]` only makes sense as the last part of the URL. 

Are you actually saying that you want to match
`foo/demo/flowers/` as well as `foo/bar/baz/demo/flowers` ???

I think we should throw an error if the `[...__]` is not last port of the URL,  I can fix that....

**Comment by robisim74** [comment] 2023-08-29 17:21
@mhevery _The [...lang] only makes sense as the last part of the URL_ And since when? optional segments are planned and have been running since Qiwk City was made. Now why from version 1.2.8 they don't work anymore? This is a breaking change that breaks entire apps that are in production. You should release Qwik 2.0

**Comment by mhevery** [comment] 2023-08-29 17:28
Can you tell me more about the use case, please? Why do you need `[...lang]`? Why is `[lang]` not enough? 

My concern is how is this to be interpreted. `[...lang]/[...rest]` Who gets what?

**Comment by robisim74** [comment] 2023-08-29 17:42
I'll explain the use case, but the fact remains that _this issue is a regression in Qwik_.

When building a localized router for SEO reasons, the language parameter must be at the root of the path: https://developers.google.com/search/docs/specialty/international/managing-multi-regional-sites

Normally, the default language, in order not to be a repetition of the domain (such as `myexample.it/it-IT`) _has an url without the language parameter_, while the others do. Since Qwik's router is file-based, `[...lang]` is the only way to create it.

In `qwik-speak `I suggest to use this Qwik City feature to create a localized routing from the beginning: https://robisim74.gitbook.io/qwik-speak/library/tutorial-routing#routing

**Comment by mhevery** [comment] 2023-08-29 18:20
Ahh? I see you want `/foo/` and `/it-IT/foo` to both route to `foo/index.tsx`. The issue is that now `/anything/it-IT/foo` will route there, which I assume you don't want.

So I think you want something like `[lang?]/foo`, which will match both `/foo` as well as `/it-IT/foo` but not `/anything/it-IT/foo`

As far as the regression goes, any fix is potentially a regression if you are relying on buggy behavior. I don't think `[...lang]` was ever intended to be used in places other than at the end of the URL, the fact that it worked was just a coincidence.

OK, but let's figure out a way forward here...

Here are potential solutions:
`path/[...param]` at the end of the URL matches the remainder of the URL, but `[...param]/path` will optionally match a single path segment.

Would that be acceptable?

**Comment by robisim74** [comment] 2023-08-29 19:32
_the fact that it worked was just a coincidence_

Exactly one year ago, I personally did a pr to fix the same problem: https://github.com/BuilderIO/qwik/pull/1077 Qwik was still in alpha release (0.0.33)

Never read in Qwik docs that optional segments shoud be at the end of the url: https://qwik.builder.io/docs/routing/#dynamic-route-segments.

Up to version 1.2.7 it worked fine, but now, following a patch release (1.2.8) it doesn't work anymore: so for me it's still a regression. If it is intended, it is a breaking change, and a new major version is required.

That said, _the only acceptable thing would be that Qwik City natively offers the possibility to have an optional parameter at the root of the path (the `locale` already in Qwik?)_. But keep in mind that many developers may be using an optional parameter at the root of the path that has nothing to do with the language (this issue).

**Comment by mhevery** [comment] 2023-08-29 19:45
First, your tone of voice could be more helpful here. I am trying to resolve the issue and do the right thing, and your tone of voice is angry. Please treat others the way you want to be treated.

Second, It would have been nice to have an explicit test for this, so that there would not have been a regression.

**Comment by robisim74** [comment] 2023-08-29 20:17
Sorry about the tone. I've only tried to explain.

**Closed** 2023-08-29 22:22 UTC
Labels: TYPE: bug, STATUS-1: needs triage
