### ISSUE TITLE
[🐞] Props spreading (e.g. <input {...props} />) Typescript incompatibility

### ISSUE THREAD

**Issue by wsow4** [BuilderIO/qwik#4946] opened 2023-08-16 08:45 UTC
### Which component is affected?

Qwik Runtime

### Describe the bug

I'm trying to deal with props spreading so I can make the API of my components more flexible.

Example:
```
type Props = {
  text: string;
} & HTMLAttributes<HTMLButtonElement>

const MyButton = component$(({ text, ...props }: Props) => {
  return <button {...props}>{text}</button>
});
```

In React you can do something like this (repo: https://stackblitz.com/edit/react-ts-do296w?file=index.tsx): 
```
type Props = {
  text: string;
} & ButtonHTMLAttributes<HTMLButtonElement>
```

but not in Qwik.

You can see in the reproduction playground that everything works in general, except Typescript throws some errors.

### Reproduction

https://qwik.builder.io/playground/#v=1.1.5&f=Q040BmZm2FKNjoJHiK%2BPYwkwUIBVf2qxDqhoLXCDhiqIjTvSQAEBCQFwlWwADAPkhAVuQmCkrkxw7V2tp6cHlq8F%2BQKUvpBNMsRmkhWaS21AXLBy15xUUIazI8suI%2Bx2YYQClawzxmEdqNkBbAER8iJ5lprgt5QIv5JgLzjXgzWbQpKPLVgfSNhKQR1Unqkr1CioQxoQ6ly1CmrE%2Bx7FV6YovrJBstJOQwNmpQ6QhrkR6D7svgAptK0GkbXYfERC4Yme5aEZA1idlKbaqhuoI%2BVZaEqHShliSBnBpIwwpIxhUsYYUiYwKRMMKVOYlKk6xMdKoMhQgilDFByjpf2QLO0B

### Steps to reproduce

1. Go to the provided Qwik playground.
2. Notice everything works as expected, but Typescript throws errors.

### System Info

```shell
System:
    OS: macOS 13.5
    CPU: (10) arm64 Apple M1 Pro
    Memory: 12.77 GB / 32.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.5.0 - ~/.nvm/versions/node/v20.5.0/bin/node
    npm: 9.8.0 - ~/.nvm/versions/node/v20.5.0/bin/npm
  Browsers:
    Chrome: 115.0.5790.114
    Safari: 16.6
```

**Comment by MaieulChevalier** [comment] 2023-08-28 09:40
+1

On my end, I'm trying to create a reusable Input component with tailwind, but I get a typescript error saying children types are incompatible. I suspect this to be a bug but I'm far from being a typescript wizard so I'm not certain.

### First attempt:

I first tried the following approach

```typescript
type InputProps = QwikIntrinsicElements["input"] & {
  classExtension?: string;
};

export default component$(({ classExtension, ...props }: InputProps) => {
  return (
    <input
      {...props}
      class={cn(
        "flex h-10 w-full ...",
        classExtension,
      )}
    />
  );
});
```

But I got following typescript error:

> Type '{ class: string; accessKey?: string | undefined; contentEditable?: "true" | "false" | "inherit" | undefined; contextMenu?: string | undefined; dir?: "ltr" | "rtl" | "auto" | undefined; ... 633 more ...; "window:onWaiting$"?: SingleOrArray<...> | undefined; }' is not assignable to type 'InputHTMLAttributes<HTMLInputElement>'.
  Types of property 'children' are incompatible.
    Type 'JSXChildren' is not assignable to type 'undefined'.
      Type 'null' is not assignable to type 'undefined'.
      

### chatgpt suggestion

Then I tried suggestion from chatgpt ([see conversation](https://chat.openai.com/share/bc328c56-4b06-4922-be5d-d1b1760b7e1a)):

```typescript
type InputProps = Omit<QwikIntrinsicElements["input"], "children"> & {
  classExtension?: string;
};

export default component$(({ classExtension, ...props }: InputProps) => {
  return (
    <>
      <input
        {...props}
        class={cn(
          "flex h-10 w-full ...",
          classExtension,
        )}
      />
    </>
  );
});
```

It works, but it feels a bit like a workaround or @ts-ignore.

### Cause

After some investigation, I found out that the [HTMLAttributes extends DOMAttributes<T>](https://github.com/BuilderIO/qwik/blob/ac1e4af1a76ef03e16850d902058ded24e0a08b6/packages/qwik/src/core/render/jsx/types/jsx-generated.ts#L323) [which has a children?: JSXChildren type](https://github.com/BuilderIO/qwik/blob/ac1e4af1a76ef03e16850d902058ded24e0a08b6/packages/qwik/src/core/render/jsx/types/jsx-qwik-attributes.ts#L269). Removing that type or removing that DOMAttributes<T> extension seems to solve the issue, but I don't know if that will not create issues elsewhere...

**Comment by mhevery** [comment] 2023-08-28 17:12
Correct adding `Omit<T, 'children'>` fixes the issue

https://qwik.builder.io/playground/#v=1.1.5&f=7VY7DoJAEO09xYbCoSCEbyEBEguNhcbGGxgKEk1MxAq5uzMDG8FdAYmNiQ2%2Fx%2B6%2BefPtBI2%2F0EWNJTaH3XZZoCjY%2BrOrRaX1sm5Upef3TiMhagW4JTuoQTuweIRQoivn7l3ats14RVZQfLV3cnU7RWJ%2Fzou4S5dfec3qlFHWoT%2FhSOUc3Q3ppNO9ntMVcQYIiEkM%2FD4GNKDgrDSkwxeECEbQGCHIVCZcPninsI7DhNfR50gAFUYQdwH1JAKzSsyxc4wUp2Nn2LEzbh2ZmqY80sK75Ij89FbQj0lJ10pn0QdV%2BLV2NBmGfemWJeBAK%2FmblGkgV4E8CXkK5EvIV6BAQoEChRIKobbYIGcY8rdnBfq3jZ9sGw8

**Comment by maiieul** [comment] 2023-10-26 12:58
Following a discussion on discord (https://discord.com/channels/842438759945601056/1046929728948408370), `Omit<T, 'children'>` will prevent autocomplete to work for special Qwik attributes that use the $ sign (perhaps for other special attributes too).

I think I've found a better workaround, which is to extract the children prop from the other destructured properties.

So instead of 

```tsx
const Input1 = component$<Omit<QwikIntrinsicElements["input"], 'children'>>((props) => {
  return <input {...props} />
});
```

You can do

```tsx
const Input2 = component$<QwikIntrinsicElements["input"]>(({children:_, ...props}) => {
  return <input {...props} />
});
```

For which you will need custom eslint rule

```cjs
    "@typescript-eslint/no-unused-vars": [
      "error",
      {
        argsIgnorePattern: "^_",
        varsIgnorePattern: "^_",
        caughtErrorsIgnorePattern: "^_",
      },
    ],
 ```

To prevent typescript [@typescript-eslint/no-unused-vars](https://typescript-eslint.io/rules/no-unused-vars) error from firing.

This way you can get auto-complete working for special $ attributes (e.g. `onClick$`).


### Repro:
https://qwik.builder.io/playground/#v=1.2.14&f=Q0o0JkZYE40O2GZPYLRm5hVnJrvmpEKKXnxpCeJpcC1sCPQ2wjAb%2F9zMEhusBkYrZYLUK8XqKKgng0pbYGyo29lpaIDbGRhJEKxYoVpPTw8sXwvyKigRIttthGo3fmuBNlXD7LWK11GAm0y81aTkIfSYhwYWUoxBvQATQcTaaFYbklkNAA

Try to add onClick$ to `<Input1 />` and you won't see the auto-complete. But if you do on `<Input2 />` it will work.

I think it's fine to "omit" the children prop with `children:_`, since qwik components with component$ use `<Slot />` anyway. Please tell me if I'm wrong :see_no_evil: 

### Root cause

children type from `QwikIntrinsicElements["input"]` and similar elements is `undefined` by default but gets converted to `(property) children?: PropFnInterface<unknown[], unknown> | undefined` when used inside component$

But in the JSX template, <input/> tag's children is of type `(property) InputHTMLAttributes<HTMLInputElement>.children?: undefined`

### Potential Fix 

Maybe we can prevent component$ from adding PropFnInterface<unknown[], unknown> to children for self-closing elements like <input  />.

**Comment by mhevery** [comment] 2023-10-26 14:15
can you propsoe a PR?

**Comment by maiieul** [comment] 2023-10-26 15:08
I'll give it a try!

**Closed** 2023-11-10 18:58 UTC
Labels: TYPE: bug, STATUS-1: needs triage
